"""Loose regression test for lib-say.

For each phrase in corpus.tsv, runs the CLI to capture:
  - phoneme_stream  (logic check, exact match required)
  - sample_count    (timing check, ±5% tolerance per render path)

Compares against expected/baseline.tsv. Sample-count tolerance is loose so
benign synthesis tweaks (amp scaling, formant tilt, etc.) don't cry wolf —
only structural regressions trip the test.

Usage:
    python tests/regression.py            # run checks (returns non-zero on regression)
    python tests/regression.py --update   # rewrite expected/baseline.tsv from current build
"""
from __future__ import annotations

import pathlib
import re
import struct
import subprocess
import sys
import tempfile
import wave

ROOT = pathlib.Path(__file__).resolve().parent.parent
TTS = ROOT / "bin" / "tts.exe"
CORPUS = pathlib.Path(__file__).resolve().parent / "corpus.tsv"
BASELINE = pathlib.Path(__file__).resolve().parent / "expected" / "baseline.tsv"

DURATION_TOLERANCE_PCT = 5.0


def load_corpus() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for line in CORPUS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        sample_id, text = line.split("\t", 1)
        rows.append((sample_id, text))
    return rows


def load_baseline() -> dict[tuple[str, str], str]:
    """{(sample_id, check_name): expected_value} from baseline.tsv."""
    if not BASELINE.exists():
        return {}
    out: dict[tuple[str, str], str] = {}
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t", 2)
        if len(parts) != 3:
            continue
        sample_id, check, value = parts
        out[(sample_id, check)] = value
    return out


def write_baseline(rows: list[tuple[str, str, str]]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by tests/regression.py --update",
        "# Loose regression baseline. Phoneme streams must match exactly;",
        "# sample counts are checked with a +/-5% tolerance.",
        "# Columns: sample_id<TAB>check<TAB>value",
        "",
    ]
    for sample_id, check, value in rows:
        lines.append(f"{sample_id}\t{check}\t{value}")
    BASELINE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def extract_phoneme_stream(debug_text: str) -> str:
    """Pulls the single line under `phoneme_stream:` from a debug report."""
    lines = debug_text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == "phoneme_stream:":
            if i + 1 < len(lines):
                return lines[i + 1].strip()
    raise RuntimeError("phoneme_stream header not found in debug report")


def get_phoneme_stream(text: str) -> str:
    result = subprocess.run(
        [str(TTS), text, "--debug-report", "-", "--dry-run", "--lang", "en"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"--debug-report failed: {result.stderr}")
    return extract_phoneme_stream(result.stdout)


def get_sample_count(text: str, amiga: bool) -> int:
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        out_path = tmp.name
    try:
        cmd = [str(TTS), text, "-o", out_path, "--lang", "en"]
        if amiga:
            cmd.append("--amiga")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"render failed: {result.stderr}")
        with wave.open(out_path, "rb") as w:
            return w.getnframes()
    finally:
        pathlib.Path(out_path).unlink(missing_ok=True)


def check_within_tolerance(actual: int, expected: int) -> tuple[bool, float]:
    if expected == 0:
        return actual == 0, 0.0
    pct = (actual - expected) / expected * 100.0
    return abs(pct) <= DURATION_TOLERANCE_PCT, pct


def collect(corpus: list[tuple[str, str]]) -> list[tuple[str, str, str]]:
    """Capture all values from the current build. Used both for --update
    and for the value side of the comparison."""
    rows: list[tuple[str, str, str]] = []
    for sample_id, text in corpus:
        rows.append((sample_id, "phonemes", get_phoneme_stream(text)))
        rows.append((sample_id, "biquad_samples", str(get_sample_count(text, amiga=False))))
        rows.append((sample_id, "amiga_samples",  str(get_sample_count(text, amiga=True))))
    return rows


def cmd_update(corpus: list[tuple[str, str]]) -> int:
    print(f"Capturing baseline for {len(corpus)} phrases...")
    rows = collect(corpus)
    write_baseline(rows)
    print(f"Wrote {BASELINE} ({len(rows)} entries)")
    return 0


def cmd_check(corpus: list[tuple[str, str]]) -> int:
    expected = load_baseline()
    if not expected:
        print(f"No baseline at {BASELINE} — run with --update first", file=sys.stderr)
        return 2

    failures: list[str] = []
    print(f"{'sample':22} {'check':18} {'status':10}  detail")
    print("-" * 78)
    for sample_id, text in corpus:
        # phonemes
        actual = get_phoneme_stream(text)
        want = expected.get((sample_id, "phonemes"))
        if want is None:
            failures.append(f"{sample_id} phonemes: no baseline")
            print(f"{sample_id:22} {'phonemes':18} MISSING")
        elif actual == want:
            print(f"{sample_id:22} {'phonemes':18} ok")
        else:
            failures.append(f"{sample_id} phonemes:\n    expected: {want}\n    got:      {actual}")
            print(f"{sample_id:22} {'phonemes':18} FAIL      stream differs")

        # sample counts
        for check in ("biquad_samples", "amiga_samples"):
            amiga = check.startswith("amiga")
            actual_n = get_sample_count(text, amiga=amiga)
            want_str = expected.get((sample_id, check))
            if want_str is None:
                failures.append(f"{sample_id} {check}: no baseline")
                print(f"{sample_id:22} {check:18} MISSING")
                continue
            want_n = int(want_str)
            ok, pct = check_within_tolerance(actual_n, want_n)
            if ok:
                print(f"{sample_id:22} {check:18} ok        {actual_n:>6} vs {want_n:>6} ({pct:+.1f}%)")
            else:
                failures.append(
                    f"{sample_id} {check}: {actual_n} vs {want_n} ({pct:+.1f}%, "
                    f"exceeds +/-{DURATION_TOLERANCE_PCT}%)"
                )
                print(f"{sample_id:22} {check:18} FAIL      {actual_n:>6} vs {want_n:>6} ({pct:+.1f}%)")

    print()
    if failures:
        print(f"FAILED ({len(failures)} regression(s)):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"PASSED ({len(corpus)} phrases x 3 checks)")
    return 0


def main(argv: list[str]) -> int:
    if not TTS.exists():
        print(f"Missing {TTS} — run cmake build first", file=sys.stderr)
        return 2

    corpus = load_corpus()

    if "--update" in argv:
        return cmd_update(corpus)
    return cmd_check(corpus)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
