/*
 * Concatenated port of the Amiga narrator's phonet family:
 *   phonet.c (top-level Phonet entry + globals)
 *   phonetc4..c10.c (per-segment track generators)
 *   phonetf0.c (per-syllable F0 contour)
 *
 * Generated by build/port_phonet.py from reference/amiga-say/narrator/.
 * Run that script after pulling new reference sources to regenerate.
 *
 * The original files share globals via extern declarations in phonetsubs.h.
 * Concatenating them into a single translation unit keeps those globals
 * file-local without changing the references that span the original files.
 */

#include "say_amiga_compat.h"
#include "say_amiga_parms.h"
#include "say_amiga_phonet.h"
#include "say_amiga_pc.h"
#include "say_amiga_phonet_subs.h"

/* Forward declarations for the per-class sub-functions called from Phonet().
 * These are defined later in this same translation unit (concatenated from
 * phonetc4..c10.c). Keep the prototypes in sync with the bodies below. */

void PhonetC4(void);
void PhonetC5(void);
void PhonetC6(void);
void PhonetC7(struct narrator_rb *iorb, ULONG centphon, ULONG centpct);
void PhonetC8(void);
void PhonetC9(void);
void PhonetC10(struct narrator_rb *iorb);
void PhonetF0(UBYTE *coef);
void PhonetInterp(const char *name, struct PhonetParms *p);
void FillBuffer(struct PhonetParms *p);
int  PrintParms(UBYTE pc);


/* ===== phonet.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

#define AVBIAS		   0		/* AV bias control		    */
#define AFBIAS		   0		/* duh				    */
#define AHBIAS		   3		/* duh				    */
#define LOCAL_BFR_SIZE	 128
#define	MIN_DBAMP	  23		/* Minimum amplitude for audibility */

/* Flags byte in coef buffer 6(An) */
#define	FF_PHONSTART	0X01
#define	FF_WORDSTART	0X02
#define FF_SYLSTART	0X04
#define FF_UNUSED	0X08
#define FF_NASAL_OR_VB	0X10
#define	FF_ASP		0X20
#define FF_FRIC		0X40
#define	FF_VOICED	0X80

#define NCOEFBYTES	8		/* Number of bytes in coef frame */
#define OF_F0		7		/* Offset to F0 element		 */

struct	PhonetParms  F0;
struct	PhonetParms  F1;
struct	PhonetParms  F2;
struct	PhonetParms  F3;
struct	PhonetParms  A1;
struct	PhonetParms  A2;
struct	PhonetParms  A3;
struct	PhonetParms  AV;
struct	PhonetParms  AF;
struct	PhonetParms  AH;
struct	PhonetParms  MH;
struct	PhonetParms  MW;

#define NTRACKS 12			/* Number of Phonet tracks	    */

UBYTE	Old_PC;				/* Phon to the left of Last Phon    */
ULONG	Old_PCF;			/* Features of phon 2 to the left   */

UBYTE	Last_PC;			/* Previous segment's phoneme code  */
ULONG	Last_PCF;			/* Features of previous phoneme	    */
UBYTE	Last_PCS;			/* Stress of previous phoneme	    */
UBYTE	Last_dur;			/* Duration of previous phoneme	    */
UBYTE	Last_bits;			/* Syll & seg bits for F0           */

UBYTE	This_PC;			/* This segment's phoneme code	    */
ULONG	This_PCF;			/* Features of current phoneme	    */
UBYTE	This_PCS;			/* Stress of current phoneme	    */
UBYTE	This_dur;			/* Duration of current phoneme	    */
UBYTE	This_bits;			/* Syll & seg bits for F0           */ 

UBYTE	Next_PC;			/* Next segment's phoneme code	    */
ULONG	Next_PCF;			/* Features of next phoneme         */
UBYTE	Next_PCS;			/* Stress of next phoneme	    */
UBYTE	Next_dur;			/* Duration of next phoneme   	    */
UBYTE	Next_bits;			/* Syll & seg bits for F0           */

BOOL syllstart,termassign;		/* Flags for F0			    */
WORD LastCR, ThisCR;			/* Continuation rises		    */
WORD F0delta, F0start, F0peak, F0end;	/* F0 values per syllable	    */

WORD Manner, PrevManner;
WORD Burstdur, Buramp, Aspamp, Aspdux, Aspam1, Aspdur;

UBYTE BperTable[NUMMANNERCLASSES][NUMMANNERCLASSES] = 
  {
    50, 35, 50, 75,
    65, 50, 50, 65,
    50, 50, 50, 75,
    25, 35, 25, 50
  };

UBYTE Tcobst[NUMTCOBSTS][2] =
  {
    {PC_B,   6},  {PC_CH, 10},  {PC_D,   8},  {PC_DH,  8},  {PC_DX, 4},
    {PC_UL,  8},  {PC_UM,  6},  {PC_UN,  8},  {PC_F,   6},  {PC_J, 10},
    {PC_G,  10},  {PC_GX, 10},  {PC_HH,  8},  {PC_HX,  8},
    {PC_KX, 10},  {PC_K,  10},  {PC_M,   6},  {PC_NX, 10},
    {PC_N,   8},  {PC_P,   8},  {PC_Q,   8},  {PC_SH, 10},
    {PC_QX , 8},  {PC_S,   8},  {PC_TH,  8},  {PC_TQ,  8},
    {PC_T,   8},  {PC_V,   6},  {PC_ZH, 10},  {PC_Z,   8}
  };

UBYTE Burdur[NUMBURDURS][2] =
  {
    {PC_B,  1},  {PC_CH, 7},  {PC_D,  1},  {PC_DX, 1},  {PC_G,  1},
    {PC_GX, 1},  {PC_J,  6},  {PC_KX, 2},  {PC_K,  2},  {PC_M,  0},
    {PC_NX, 0},  {PC_N,  0},  {PC_P,  1},  {PC_TQ, 0},  {PC_T,  2}
  };

UBYTE Diphtran[NUMDIPHTRANS][3] =
  {
    {PC_AA,   0, 80},  {PC_AE,  10, 75},  {PC_AH,   0,  0},
    {PC_AO,  11, 80},  {PC_AW,  12, 70},  {PC_AXR, 13, 40},
    {PC_AY,  10, 55},  {PC_EH,   6, 70},  {PC_ER,  18, 50},
    {PC_EXR, 10, 65},  {PC_EY,  14, 55},  {PC_IH,   9, 65},
    {PC_IXR, 10, 50},  {PC_IY,  20, 45},  {PC_OW,  12, 50},
    {PC_OXR, 11, 60},  {PC_OY,  10, 60},  {PC_UH,   9, 65},
    {PC_UW,  14, 55},  {PC_UXR, 15, 50},  {PC_YU,  10, 45}
  };

UBYTE PlosAspID[][6] =
  {      /*    P       T       K       KX      CH    */
    {PC_IY, ASP_EH, ASP_IH, ASP_IY, ASP_IH, ASP_IH},
    {PC_IXR,ASP_IH, ASP_IH, ASP_IY, ASP_IH, ASP_IH},
    {PC_Y,  ASP_IH, ASP_IH, ASP_IY, ASP_IH, ASP_IH},
    {PC_YU, ASP_IH, ASP_IH, ASP_IY, ASP_IH, ASP_IH},
    {PC_IH, ASP_AXP,ASP_IH, ASP_IH, ASP_IH, ASP_IH},
    {PC_IX, ASP_IH, ASP_IH, ASP_IH, ASP_IH, ASP_IH},
    {PC_EXR,ASP_AXP,ASP_EH, ASP_IH, ASP_IH, ASP_EH}, /* k,kx was eh */
    {PC_EY, ASP_AXP,ASP_EH, ASP_IH, ASP_IH, ASP_EH}, /* k,kx was eh */
    {PC_EH, ASP_AXP,ASP_EH, ASP_IH, ASP_IH, ASP_EH}, /* k,kx was eh */
    {PC_AE, ASP_AXP,ASP_EH, ASP_IH, ASP_EH, ASP_EH},
    {PC_AXP,ASP_AXP,ASP_AXP,ASP_IH, ASP_AXP,ASP_AXP},
    {PC_AW, ASP_AH, ASP_AE, ASP_IH, ASP_AH, ASP_AH},
    {PC_UH, ASP_UH, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_UW, ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_UXR,ASP_UW, ASP_UW, ASP_IH, ASP_UW ,ASP_UW},
    {PC_OW, ASP_AH, ASP_AH, ASP_IH, ASP_AH, ASP_AH},
    {PC_AH, ASP_AH, ASP_AH, ASP_IH, ASP_AH, ASP_AH},
    {PC_AX, ASP_AH, ASP_AH, ASP_IH, ASP_AH, ASP_AH},
    {PC_AA, ASP_AH, ASP_AXP,ASP_IH, ASP_AXP,ASP_AH},
    {PC_AXR,ASP_UH, ASP_AXP,ASP_IH, ASP_AXP,ASP_AH}, /* p was ah */
    {PC_AY, ASP_AH, ASP_AXP,ASP_IH, ASP_AXP,ASP_AH},
    {PC_AO, ASP_UH, ASP_AXP,ASP_IH, ASP_AXP,ASP_AH},
    {PC_ER, ASP_ER, ASP_ER, ASP_ER, ASP_ER, ASP_ER},
    {PC_RR, ASP_ER, ASP_ER, ASP_ER, ASP_ER, ASP_ER},
    {PC_OY, ASP_OW, ASP_AH, ASP_IH, ASP_OW, ASP_AH},
    {PC_OXR,ASP_OW, ASP_AH, ASP_IH, ASP_OW, ASP_AH},
    {PC_L,  ASP_UW, ASP_OW, ASP_IH, ASP_AXP,ASP_UH}, /* p was uw */
    {PC_UL, ASP_OW, ASP_OW, ASP_IH, ASP_AXP,ASP_UH},
    {PC_W,  ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_WH, ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_M,  ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_N,  ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_NX, ASP_UW, ASP_AXP,ASP_IH, ASP_AXP,ASP_UH},
    {PC_HH, ASP_AXP,ASP_UH, ASP_IH, ASP_AXP,ASP_UH},
    {PC_HX, ASP_AXP,ASP_UH, ASP_IH, ASP_AXP,ASP_UH},
    {PC_UM, ASP_AXP,ASP_UH, ASP_IH, ASP_AXP,ASP_UH},
    {PC_UN, ASP_AXP,ASP_UH, ASP_IH, ASP_AXP,ASP_UH}
  };

WORD 	 LocalBfr[NTRACKS*LOCAL_BFR_SIZE];	/* Local buffer		*/

WORD	*LocalF1;				/* Local buffer ptrs	*/
WORD	*LocalF2;
WORD	*LocalF3;
WORD	*LocalA1;
WORD 	*LocalA2;
WORD	*LocalA3;
WORD 	*LocalAV;
WORD 	*LocalAF;
WORD 	*LocalAH;
WORD 	*LocalF0;
WORD 	*LocalMH;
WORD 	*LocalMW;

WORD	*TempF1, *TempF2, *TempF3;
WORD	*TempA1, *TempA2, *TempA3;
WORD	*TempAV, *TempAF, *TempAH;
WORD    *TempF0, *TempMH, *TempMW;

UBYTE	*f0start, *f0peak, *f0end, *f0cr;	/* These pointers are global. */

void Phonet(phon, stress, dur, coef, F0START, F0PEAK, F0END, F0CR, mouths,
	    iorb, centphon, centpct)
	  UBYTE	  *phon, *stress, *dur;
register  UBYTE	  *coef;
	  UBYTE	  *F0START, *F0PEAK, *F0END, *F0CR;
	  UBYTE	  *mouths;
struct	  narrator_rb	*iorb;
	  ULONG	   centphon, centpct;
{
extern 	struct PhonemeParms	Parms[];
extern	void			PhonetInterp();
extern	void			FillBuffer();
extern	int			PrintParms();
extern	void			AdjustTrack();
extern	void		   	PhonetC4();
extern	void		   	PhonetC5();
extern	void		   	PhonetC6();
extern	void		        PhonetC7();
extern	void		   	PhonetC8();
extern	void		   	PhonetC9();
extern	void		   	PhonetC10();
extern	void			PhonetF0();
	UBYTE 			firstdur;
	WORD			i,j,k,index;
	WORD			half_dur;
	WORD			artic;		/* local articulation coef */
	ULONG			flags;
	UBYTE			fricid;
	UBYTE			aspid;
	UBYTE			nasalid;
	BOOL			nasal_f;
	BOOL			sylnasal_f;
	BOOL			voiced_plosive_f;
	BOOL			use_left_fricid;
	BOOL			wordfinal;
	BOOL			mouthflag;

   /*  
    *  The lowercase array names are for the GLOBAL pointers. The uppercase
    *  names are for the args passed to Phonet from main.
    */

    f0start = F0START;
    f0peak  = F0PEAK;
    f0end   = F0END;
    f0cr    = F0CR;

    termassign = syllstart = FALSE;

   /*
    *	Initialization.
    *	   Set Local to beginning of local interp area.
    *	   Initialize first frame with QX targets.
    */

    LocalF1 = &LocalBfr[0*LOCAL_BFR_SIZE];	/* Initialize local bfr ptrs */
    LocalF2 = &LocalBfr[1*LOCAL_BFR_SIZE];
    LocalF3 = &LocalBfr[2*LOCAL_BFR_SIZE];
    LocalA1 = &LocalBfr[3*LOCAL_BFR_SIZE];
    LocalA2 = &LocalBfr[4*LOCAL_BFR_SIZE];
    LocalA3 = &LocalBfr[5*LOCAL_BFR_SIZE];
    LocalAV = &LocalBfr[6*LOCAL_BFR_SIZE];
    LocalAF = &LocalBfr[7*LOCAL_BFR_SIZE];
    LocalAH = &LocalBfr[8*LOCAL_BFR_SIZE];
    LocalF0 = &LocalBfr[9*LOCAL_BFR_SIZE];
    LocalMH = &LocalBfr[10*LOCAL_BFR_SIZE];
    LocalMW = &LocalBfr[11*LOCAL_BFR_SIZE];

    F1.Local  = F1.Cumdur  = LocalF1;
    F2.Local  = F2.Cumdur  = LocalF2;
    F3.Local  = F3.Cumdur  = LocalF3;
    A1.Local  = A1.Cumdur  = LocalA1;
    A2.Local  = A2.Cumdur  = LocalA2;
    A3.Local  = A3.Cumdur  = LocalA3;
    AV.Local  = AV.Cumdur  = LocalAV;
    AF.Local  = AF.Cumdur  = LocalAF;
    AH.Local  = AH.Cumdur  = LocalAH;
    F0.Local  = F0.Cumdur  = LocalF0;
    MH.Local  = MH.Cumdur  = LocalMH;
    MW.Local  = MW.Cumdur  = LocalMW;

    firstdur  = *dur & 0X3F;			/* Assign old durations	*/
    F1.Olddur = firstdur;
    F2.Olddur = firstdur;
    F3.Olddur = firstdur;
    A1.Olddur = firstdur;
    A2.Olddur = firstdur;
    A3.Olddur = firstdur;
    AV.Olddur = firstdur;
    AF.Olddur = firstdur;
    AH.Olddur = firstdur;
    F0.Olddur = firstdur;
    MH.Olddur = firstdur;
    MW.Olddur = firstdur;

    while (firstdur--)
      {
	*F1.Cumdur++ = Parms[PC_QX].f1;
	*F2.Cumdur++ = Parms[PC_QX].f2;
	*F3.Cumdur++ = Parms[PC_QX].f3;
	*A1.Cumdur++ = Parms[PC_QX].a1;
	*A2.Cumdur++ = Parms[PC_QX].a2;
	*A3.Cumdur++ = Parms[PC_QX].a3;
	*AV.Cumdur++ = 0;
	*AF.Cumdur++ = 0;
	*AH.Cumdur++ = 0;
	*F0.Cumdur++ = 110 >> 1;
	*MH.Cumdur++ = Parms[PC_M].height;
	*MW.Cumdur++ = Parms[PC_M].width;
	*(coef + NCOEFBYTES*firstdur + OF_F0) = 110 >> 1;
      }

#ifdef DEBUG
    firstdur = LOCAL_BFR_SIZE - (*dur & 0X3F);
    TempF1 = F1.Cumdur;
    TempF2 = F2.Cumdur;
    TempF3 = F3.Cumdur;
    TempA1 = A1.Cumdur;
    TempA2 = A2.Cumdur;
    TempA3 = A3.Cumdur;
    TempAV = AV.Cumdur;
    TempAF = AF.Cumdur;
    TempAH = AH.Cumdur;
    TempF0 = F0.Cumdur;
    TempMH = MH.Cumdur;
    TempMW = MW.Cumdur;
	  
    while (firstdur--)
      {
	*TempF1++ = -99;
	*TempF2++ = -99;
	*TempF3++ = -99;
	*TempA1++ = -99;
	*TempA2++ = -99;
	*TempA3++ = -99;
	*TempAV++ = -99;
	*TempAF++ = -99;
	*TempAH++ = -99;
	*TempF0++ = -99;
	*TempMH++ = -99;
	*TempMW++ = -99;
      }
#endif

    F1.Oldval = *(F1.Cumdur - 1);		/* Assign Oldvals	*/
    F2.Oldval = *(F2.Cumdur - 1);
    F3.Oldval = *(F3.Cumdur - 1);
    A1.Oldval = *(A1.Cumdur - 1);
    A2.Oldval = *(A2.Cumdur - 1);
    A3.Oldval = *(A3.Cumdur - 1);
    AV.Oldval = *(AV.Cumdur - 1);
    AF.Oldval = *(AF.Cumdur - 1);
    AH.Oldval = *(AH.Cumdur - 1);
    F0.Oldval = *(F0.Cumdur - 1);
    MH.Oldval = *(MH.Cumdur - 1);
    MW.Oldval = *(MW.Cumdur - 1);

    F0.Target = 110 >> 1;

    DBG(printf("coef=%lx    dur=%lx after first qx \n",coef,dur));

    Last_PC  = PC_QX;
    Last_PCF = Parms[Last_PC].features;
    Last_bits= 0;

    This_PC  = *phon++;
    This_PCF = Parms[This_PC].features;
    This_PCS = *stress   & 0X10;
    This_bits= *stress++ & 0xf0;
    This_bits |= (*dur & 0xc0) >> 4;
    This_dur = *dur++ & 0X3F;

    Next_PC  = *phon++;
    Next_PCF = Parms[Next_PC].features;
    Next_PCS = *stress   & 0X10;
    Next_bits= *stress++ & 0xf0;
    Next_bits |= (*dur & 0xc0) >> 4;
    Next_dur = *dur++ & 0X3F;

    ThisCR = LastCR = 0;			/* Init F0 variables    */
    F0start = F0peak = F0end = 110;
    F0delta = 0;

    Manner = SONMANNER;				/* If QX is not vowel	*/

    wordfinal = TRUE;
    
    mouthflag = iorb->mouths ? TRUE : FALSE;

   /*
    *	Process until end of phoneme string.
    */

    while (*phon != 0XFF)
      {
	Old_PC   = Last_PC;
	Old_PCF  = Last_PCF;
	 
	Last_PC	 = This_PC;
	Last_PCF = This_PCF;
	Last_PCS = This_PCS;
	Last_dur = This_dur;
	Last_bits= This_bits;

	This_PC  = Next_PC;
	This_PCF = Next_PCF;
	This_PCS = Next_PCS;
	This_dur = Next_dur;
	This_bits= Next_bits;

	Next_PC  = *phon++;
 	Next_PCF = Parms[Next_PC].features;
	Next_PCS = *stress & 0X10;
	Next_bits= *stress++ & 0xf0;
	Next_bits |= (*dur & 0xc0) >> 4;
	Next_dur = *dur++ & 0X3F;

	DBG(printf("working on phon=%c%c\n", Parms[This_PC].digraph >> 8,
		Parms[This_PC].digraph & 0xFF));

	DBG(PrintParms(Last_PC));
	DBG(PrintParms(This_PC));
	DBG(PrintParms(Next_PC));

   /*
    *  The Meat
    */

	F1.Mintime = F1.Olddur;
	F2.Mintime = F2.Olddur;
	F3.Mintime = F3.Olddur;
	A1.Mintime = A1.Olddur;
	A2.Mintime = A2.Olddur;
	A3.Mintime = A3.Olddur;
	AV.Mintime = AV.Olddur;
	AF.Mintime = AF.Olddur;
	AH.Mintime = AH.Olddur;
	F0.Mintime = F0.Olddur;
	MH.Mintime = MH.Olddur;
	MW.Mintime = MW.Olddur;

	PhonetC4();  
	PhonetC5();
	if (THIS_PC_IS(SONORANT) && THIS_PC_ISNOT(NASAL)) PhonetC6();
	if THIS_PC_IS(VOWEL) PhonetC7(iorb, centphon, centpct);
	if (THIS_PC_ISNOT(SONORANT) || THIS_PC_IS(NASAL)) PhonetC8();
	PhonetC9();
	PhonetC10(iorb);

	DBG(PrintPParms("F1", &F1));
	DBG(PrintPParms("F2", &F2));
	DBG(PrintPParms("F3", &F3));

        DBG(printf("\n\nFormant tracks before fillbuffer and interp\n"));
	DBG(PrintTrack("F1", &F1));
        DBG(PrintTrack("F2", &F2));

	if THIS_PC_ISNOT(DIPHTHONG)
	  {
	    FillBuffer(&F1);
	    FillBuffer(&F2);
	    FillBuffer(&F3);
	    FillBuffer(&A1);
	    FillBuffer(&A2);
	    FillBuffer(&A3);
	  }
	FillBuffer(&AV);
	FillBuffer(&AF);
	FillBuffer(&AH);
	FillBuffer(&MH);
	FillBuffer(&MW);
/*	FillBuffer(&F0); */

   /*
    *	Articulation.
    *	    Modify Tcb and Tcf according to user specified percentage.
    *       Default = 100.
    *

	if((iorb->flags & NDF_NEWIORB) && (iorb->articulate != DEFARTIC))
	{
	    artic = iorb->articulate;
	    F1.Tcf = PCT(artic, F1.Tcf);
	    F2.Tcf = PCT(artic, F2.Tcf);
	    F3.Tcf = PCT(artic, F3.Tcf);
	    A1.Tcf = PCT(artic, A1.Tcf);
	    A2.Tcf = PCT(artic, A2.Tcf);
	    A3.Tcf = PCT(artic, A3.Tcf);
	    F1.Tcb = PCT(artic, F1.Tcb);
	    F2.Tcb = PCT(artic, F2.Tcb);
	    F3.Tcb = PCT(artic, F3.Tcb);
	    A1.Tcb = PCT(artic, A1.Tcb);
	    A2.Tcb = PCT(artic, A2.Tcb);
	    A3.Tcb = PCT(artic, A3.Tcb);
	    MH.Tcb = PCT(artic, MH.Tcb);
	    MW.Tcb = PCT(artic, MW.Tcb);
	}

   /*
    *  Interpolate each parameter in its own local buffer.
    */

	PhonetInterp("F1", &F1);	/* strings are for debugging only */
	PhonetInterp("F2", &F2);
	PhonetInterp("F3", &F3);
	PhonetInterp("A1", &A1);
	PhonetInterp("A2", &A2);
	PhonetInterp("A3", &A3);
	PhonetInterp("AV", &AV);
	PhonetInterp("AF", &AF);
	PhonetInterp("AH", &AH);
	PhonetInterp("MH", &MH);
	PhonetInterp("MW", &MW);
/*	PhonetInterp("F0", &F0); */

        DBG(printf("formant tracks after interpolation\n"));
        DBG(PrintTrack("F1", &F1));
        DBG(PrintTrack("F2", &F2));

	DBG(printf("\n\n\n\n\n\n"));

   /*
    *	Install appropriate arrays into the coef buffer.
    *	    
    */

	LocalF1 = &LocalBfr[0*LOCAL_BFR_SIZE];	      /* Reset local bfr ptrs */
	LocalF2 = &LocalBfr[1*LOCAL_BFR_SIZE];
	LocalF3 = &LocalBfr[2*LOCAL_BFR_SIZE];
	LocalA1 = &LocalBfr[3*LOCAL_BFR_SIZE];
 	LocalA2 = &LocalBfr[4*LOCAL_BFR_SIZE];
	LocalA3 = &LocalBfr[5*LOCAL_BFR_SIZE];
 	LocalAV = &LocalBfr[6*LOCAL_BFR_SIZE];
 	LocalAF = &LocalBfr[7*LOCAL_BFR_SIZE];
 	LocalAH = &LocalBfr[8*LOCAL_BFR_SIZE];
 	LocalF0 = &LocalBfr[9*LOCAL_BFR_SIZE];
 	LocalMH = &LocalBfr[10*LOCAL_BFR_SIZE];
 	LocalMW = &LocalBfr[11*LOCAL_BFR_SIZE];

	if (LAST_PC_IS(SONORANT) && (Last_PC != PC_HH) && (Last_PC != PC_HX))
	     aspid = Parms[Last_PC].fricID;
	else aspid = Parms[This_PC].fricID;

	if (!(Old_PCF & VOICED) && (Old_PCF & PLOSIVE) && LAST_PC_IS(SONORANT))
	{
	    switch(Old_PC)
	    {
		case PC_P:	index = 1;	break;    
		case PC_T:	index = 2;	break;    
		case PC_K:	index = 3;	break;    
		case PC_KX:	index = 4;	break;    
		case PC_CH:	index = 5;
	    }
	    for(i=0; i<37; i++)  if(PlosAspID[i][0] == Last_PC) break;
	    aspid = PlosAspID[i][index];
	}
    
	nasal_f = LAST_PC_IS(NASAL) ? FF_NASAL_OR_VB : 0;

	if (LAST_PC_IS(VOICED) && LAST_PC_IS(PLOSIVE))
	  {
	    if(!(Old_PCF & VOICED) || !(Old_PCF & SONORANT))
		 voiced_plosive_f = 0;
	    else voiced_plosive_f = FF_NASAL_OR_VB;
	  }
	else voiced_plosive_f = 0;

	sylnasal_f	 = (!(Old_PCF & GLOTTAL) &&
			    LAST_PC_IS(NASAL)    && 
			    LAST_PC_IS(SYLLABIC)) ? TRUE : FALSE;
			    
	nasalid = 0;
	if LAST_PC_IS(NASAL) switch(Last_PC)
	  {
	    case PC_M:	    nasalid = 1;	break;
	    case PC_UM:	    nasalid = 1;	break;
	    case PC_N:	    nasalid = 2;	break;
	    case PC_UN:	    nasalid = 2;	break;
	    case PC_NX:	    nasalid = 3;	break;
	  }

	use_left_fricid = TRUE;

	half_dur = MIN(Last_dur >> 1, 5);
	for (i = 0;  i < Last_dur; ++i)
          {
	    if (i >= half_dur) use_left_fricid = FALSE;

	    if LAST_PC_IS(FRICATIVE | PLOSIVE) fricid = Parms[Last_PC].fricID;
	    else if (use_left_fricid) fricid = Parms[Old_PC].fricID;
	    else if LAST_PC_IS(PLOSIVE) fricid = Parms[Last_PC].fricID;
	    else fricid = Parms[This_PC].fricID;

	    if(iorb->flags & NDF_NEWIORB)
	    {
		*LocalAV += iorb->AVbias + AVBIAS;
		*LocalAH += iorb->AVbias + AHBIAS;
		*LocalAF += iorb->AFbias + AFBIAS;
	    }
	    else
	    {
		*LocalAV += AVBIAS;
		*LocalAH += AHBIAS;
		*LocalAF += AFBIAS;
	    }

/*	    flags = (sylnasal_f && (i < 4)) ? 0 : nasal_f;  */
	    flags = nasal_f;
	    if (*LocalAV + *LocalA1 >  MIN_DBAMP) flags |= FF_VOICED;
	    if (*LocalAF            >  MIN_DBAMP) flags |= FF_FRIC;
/*	    if (*LocalAF            <= MIN_DBAMP) flags |= voiced_plosive_f; */
	    flags |= voiced_plosive_f;
	    if (*LocalAH            >  MIN_DBAMP) flags |= FF_ASP;
	    
	    *coef++ = ((flags & nasal_f) | voiced_plosive_f) ? 
					   nasalid  : *LocalF1;
	    *coef++ = (flags  & FF_FRIC) ? fricid   : *LocalF2;
	    *coef++ = (flags  & FF_ASP ) ? aspid    : *LocalF3;
	    *coef++ = *LocalAV + *LocalA1++;
	    *coef++ = (flags  & FF_FRIC) ? *LocalAF : *LocalAV + *LocalA2;
	    *coef++ = (flags  & FF_ASP ) ? *LocalAH : *LocalAV + *LocalA3;
	    *coef++ = flags;
	    coef++;				/* Bump past F0		 */ 

	    if (mouthflag) *mouths++ = (*LocalMH++ << 4) + *LocalMW++;

	    LocalAH++;				/* Adjust local bfr ptrs */
	    LocalAF++;				/* Note that LocalA1,F0  */
	    LocalAV++;				/* and LocalMH,MW are	 */
	    LocalF1++;				/* incremented above 	 */
	    LocalF2++;
	    LocalF3++;
	    LocalA2++;
	    LocalA3++;

	  }

	PhonetF0(coef);

   /*
    *	Set start of phon, syllable, and word bits in coef buffer.
    */

	flags = FF_PHONSTART;			/* Always start of phon	*/

	if (Last_bits & 0X80) {
	    flags |= FF_SYLSTART;		/* Add in start of syl	*/
	    if (wordfinal) {
	        flags |= FF_WORDSTART;		/* Add in start of word	*/
	        wordfinal   = FALSE;
	    }
	}
	wordfinal = (wordfinal || (Last_bits & 0X08));

	*(coef - Last_dur*8 + 6) |= flags;	/* Store in coef buffer	*/

   /*
    *	Adjust phonet track pointers.
    */

	AdjustTrack(&F1);
	AdjustTrack(&F2);
	AdjustTrack(&F3);
	AdjustTrack(&A1);
	AdjustTrack(&A2);
	AdjustTrack(&A3);
	AdjustTrack(&AV);
	AdjustTrack(&AF);
	AdjustTrack(&AH);
/*	AdjustTrack(&F0); */
	AdjustTrack(&MH);
	AdjustTrack(&MW);

      }					/* End of phoneme input */

    for (i = 0; i < 8; ++i)  *coef++ = 0xff;	/* Last frame fill */

}

#ifdef PRINTDEBUGINFO

int PrintParms(int pcode)
{
   printf("    features = %lx\n", Parms[pcode].features);
   printf("    f1=%ld  f2=%ld  f3=%ld\n", (LONG)Parms[pcode].f1,
					    (LONG)Parms[pcode].f2,
					    (LONG)Parms[pcode].f3);
   printf("    a1=%ld  a2=%ld  a3=%ld\n", (LONG)Parms[pcode].a1,
					    (LONG)Parms[pcode].a2,
					    (LONG)Parms[pcode].a3);
   printf("    mindur=%ld   inhdur=%ld\n", (LONG)Parms[pcode].mindur,
   					     (LONG)Parms[pcode].inhdur);
}

int PrintPParms(char * TrackName, struct	PhonetParms * Track)
{

    printf("\n\nFinal phonet parms values for %s\n",TrackName);

    printf("Cumdur=%lx    Local=%lx    Olddur=%ld    Segdur=%ld\n",
	Track->Cumdur, Track->Local, (LONG)Track->Olddur, (LONG)Track->Segdur);

    printf("Trantype=%ld   Mintime=%ld   Target=%ld   Oldval=%ld\n",
	(LONG)Track->Trantype, (LONG)Track->Mintime, (LONG)Track->Target,
	(LONG)Track->Oldval);

    printf("Tcf=%ld   Tcb=%ld   Bper=%ld   Bvf=%ld   Bvb=%ld\n",
	(LONG)Track->Tcf, (LONG)Track->Tcb, (LONG)Track->Bper, 
	(LONG)Track->Bvf, (LONG)Track->Bvb);
}

int PrintTrack(char * DebugString, struct	PhonetParms * Track)
{
int	 i,j;
WORD	*local;

	local = Track->Local;

	printf("%s\n", DebugString);

	for (i=0; i<8; ++i) {
	    for (j=0; j<16; ++j) printf("%3d ",*local++);
	    printf("\n");
	}
}

#endif

/* ===== phonetc4.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

#define A1BIAS	-3
#define A2BIAS	0
#define A3BIAS	0

void PhonetC4()
{
UBYTE	PC;
UWORD	temp;

   /*
    *  (C.4)  Initialization.
    *
    */

   /*
    *  (C.4.1)  Set manner class.
    */

    PrevManner = Manner;

    if THIS_PC_IS(VOWEL) Manner = VOWELMANNER;
      else if THIS_PC_IS(STOP) Manner = STOPMANNER;
	else if THIS_PC_IS(FRICATIVE) Manner = FRICMANNER;
	  else Manner = SONMANNER;

   /*
    *  (C.4.2)  Set freq and amp targets from Tables C.1 and C.2.  
    *           If this seg is HH or HX, use targets from next segment.
    */

    PC = ((This_PC == PC_HH) || (This_PC == PC_HX)) ? Next_PC : This_PC;

    F1.Target = Parms[PC].f1; 
    F2.Target = Parms[PC].f2; 
    F3.Target = Parms[PC].f3; 
    
    A1.Target = Parms[PC].a1 + A1BIAS;
    A2.Target = Parms[PC].a2 + A2BIAS; 
    A3.Target = Parms[PC].a3 + A3BIAS; 

    AV.Target = Parms[This_PC].av;

    if((This_bits & PHRASEFINAL) && !This_PCS && THIS_PC_IS(VOICED))
    {
	AV.Target -= 2;
	DBG(printf("ad hoc: Unstressed phrase final voiced seg AV down 2db\n"));
    }

    AF.Target = 0;
    if THIS_PC_IS(FRICATIVE) 
      {
	switch (This_PC)
          {
	    case PC_S :     AF.Target = 50;	break;
	    case PC_SH:     AF.Target = 51;	break;
	    case PC_F :     AF.Target = 43;	break;
	    case PC_TH:     AF.Target = 41;	break;
	    case PC_V :     AF.Target = 45;	break;
	    case PC_DH:     AF.Target = 42;	break;
	    case PC_Z :     AF.Target = 53;	break;
	    case PC_ZH:     AF.Target = 48;	break;
	  }
	if (!This_PCS)
	{
	    AF.Target -= 3;		/* Ad hoc rule added 8/16/88 */
	    if(This_bits & PHRASEFINAL)  AF.Target -= 3;
	}
      }

    switch (This_PC)
      {
	case PC_HH:   AH.Target = 52;	break;
	case PC_HX:   AH.Target = 52;	break;
	case PC_WH:   AH.Target = 52;	break;
	default:      AH.Target =  0;	break;
      }

    MH.Target = Parms[This_PC].height;
    MW.Target = Parms[This_PC].width;

    F0.Segdur = This_dur;
    F1.Segdur = This_dur;
    F2.Segdur = This_dur;
    F3.Segdur = This_dur;
    A1.Segdur = This_dur;
    A2.Segdur = This_dur;
    A3.Segdur = This_dur;
    AF.Segdur = This_dur;
    AV.Segdur = This_dur;
    AH.Segdur = This_dur;
    MH.Segdur = This_dur;
    MW.Segdur = This_dur;

    /* Set Tcf from table C.3. */

    AV.Tcf = 3;
    AF.Tcf = 5;		/* was 4  */
    AH.Tcf = 3;		/* was 4  */
    F0.Tcf = 14;	/* was 12 */
    F1.Tcf = 8;		/* These all should be 10, but I just can't
    F2.Tcf = 8;		/*  bring myself to do it		    */
    F3.Tcf = 8;
    A1.Tcf = 8;
    A2.Tcf = 8;
    A3.Tcf = 8;
    MH.Tcf = 8;
    MW.Tcf = 8;
			
    Buramp = 0;
    if (THIS_PC_IS(PLOSIVE) || (This_PC == PC_DX)) switch (This_PC)
      {
	case  PC_B :	Buramp = 44;	break;
	case  PC_D :	Buramp = 46;	break;
	case  PC_G :	Buramp = 43;	break;
	case  PC_GX:	Buramp = 43;	break;
	case  PC_DX:	Buramp = 40;	break;
	case  PC_P :	Buramp = 42;	break;
	case  PC_T :	Buramp = 44;	break;
	case  PC_K :	Buramp = 46;	break;	/* was 44 */
	case  PC_KX:	Buramp = 46;	break;	/* was 44 */
	case  PC_J :	Buramp = 44;	break;
	case  PC_CH:	Buramp = 41;	break;
      }

    Aspamp   = 51;
    Aspdux   = 0;

    AV.Trantype = SETSMO;
    AF.Trantype = SETSMO;
    AH.Trantype = SETSMO;
    F0.Trantype = SETSMO;
    F1.Trantype = SETSMO;
    F2.Trantype = SETSMO;
    F3.Trantype = SETSMO;
    A1.Trantype = SETSMO;
    A2.Trantype = SETSMO;
    A3.Trantype = SETSMO;
    MH.Trantype = SETSMO;
    MW.Trantype = SETSMO;

    temp     = BperTable[PrevManner][Manner];
    AV.Bper  = temp;
    AF.Bper  = temp;
    AH.Bper  = temp;
    F0.Bper  = temp;
    F1.Bper  = temp;
    F2.Bper  = temp;
    F3.Bper  = temp;
    A1.Bper  = temp;
    A2.Bper  = temp;
    A3.Bper  = temp;
    MH.Bper  = temp;
    MW.Bper  = temp;
}

/* ===== phonetc5.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

void PhonetC5()
{
LONG	delta, incr, i;
BYTE	temp;

    DBG(printf("Entering C.5 -- General rules\n"));

   /*
    *  (C.5) General rules.
    */

    F0.Bper = 75;
    DBG(printf("rule c.5.1  set F0 bper to 75 (all contexts)\n"));

    if LAST_PC_IS(PLOSIVE)
      {
	AF.Mintime = 0;
	DBG(printf("rule c.5.2 set AF mintime to AF cumdur\n"));
      }

    if LAST_PC_ISNOT(VOICED)
      {
	F0.Trantype = DISSMO;
	AV.Trantype = DISSMO;
	DBG(printf("rule c.5.3.1 set trantype f0 and av to dissmo\n"));

/*	F0.Mintime = 0; */
      }

/*
    if (THIS_PC_IS(SILENT) && LAST_PC_ISNOT(SILENT))
      {
	Aspdux = 3;
	Aspam1 = Aspamp;
	DBG(printf("rule c.5.4  do a breathy offset into a pause\n"));
      }
*/

/*
    if (LAST_PC_IS(SONORANT) && THIS_PC_ISNOT(VOICED))
      {
	Aspdux = 1;
	DBG(printf("rule c.5.5 \n"));
      }
*/

    if (LAST_PC_IS(SONORANT) && THIS_PC_ISNOT(VOICED) && THIS_PC_IS(FRICATIVE))
      {
	AF.Cumdur  -= 2;
	AF.Segdur  += 2;
	AF.Mintime -= 2;
     	DBG(printf("rule c.5.6  start frication early\n"));
      }

/*
    if (LAST_PC_IS(SONORANT) && THIS_PC_ISNOT(VOICED) && THIS_PC_IS(STOP))
      {
	Aspam1 -= 6;
     	DBG(printf("rule c.5.7  \n"));
      }
*/

/*  
    if (Aspdux != 0)
      {
	AH.Cumdur -= 8*(Aspdux+3);
	incr	   = ((Aspam1 - *AH.Cumdur) << 5)/3;
	delta	   = *AH.Cumdur << 5;
	for (i=0; i<3; ++i)
	  {
	    AH.Cumdur  += 8;
	    *AH.Cumdur  = delta >> 5;
	    delta      += incr;
	  }
	DBG(printf("rule 5.8:  no used\n"));
      }
*/

    /*  Moving rule 5.9 after 5.13.b */

/*			F0 handled by phonetf0
    if (THIS_PC_ISNOT(VOICED) && LAST_PC_ISNOT(VOICED))
      {
	F0.Trantype = DISCON;
	DBG(printf("Rule C.5.10\n"));
      }

    if (THIS_PC_ISNOT(VOICED) && LAST_PC_IS(VOICED))
      {
	F0.Trantype = SMODIS;
	DBG(printf("Rule C.5.11\n"));
      }
*/

    if (THIS_PC_ISNOT(STOP) && LAST_PC_IS(STOP))
      {
	for (i=0; i<NUMTCOBSTS; ++i) if (Tcobst[i][0] == Last_PC) break;
	temp   = Tcobst[i][1];
	F1.Tcf = temp;
	F2.Tcf = temp;
	F3.Tcf = temp;
	A1.Tcf = temp;
	A2.Tcf = temp;
	A3.Tcf = temp;
	DBG(printf("Rule C.5.12  PC=%lx  f1..f3,a1..a3 Tcf=%ld  index=%ld\n",
		(LONG)Tcobst[i][0], (LONG)Tcobst[i][1], i));
      }

    if (THIS_PC_ISNOT(STOP) && THIS_PC_IS(VOICED))
      if LAST_PC_IS(STOP)				/* RULE MODIFIED */
        {
	  AV.Trantype = LAST_PC_IS(NASAL) ? DISCON : DISSMO;
	  AF.Trantype = DISSMO;
	  AH.Trantype = SETSMO;
	  F1.Trantype = DISSMO;
	  F2.Trantype = DISSMO;
	  F3.Trantype = DISSMO;
	  A1.Trantype = DISSMO;
	  A2.Trantype = DISSMO;
	  A3.Trantype = DISSMO;
	  DBG(printf("Rule C.5.13.a \n"));
        }

    if THIS_PC_ISNOT(VOICED)
      {
	AV.Trantype = SMODIS;
	DBG(printf("Rule c.5.9\n"));
      }

    if (LAST_PC_IS(FRICATIVE) && THIS_PC_IS(SONORANT))
      {
	AF.Trantype = SMODIS;
	DBG(printf("Rule c.5.14: New rule.. af.trantype now smodis\n"));
      }

}

/* ===== phonetc6.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

void PhonetC6()
{
LONG	delta, incr, i;
extern	void	Phonet60();
extern	void	Phonet61();
extern	void	Phonet62();

    DBG(printf("Entering C.6 -- Sonorant rules\n"));

    Phonet60();

    if (LAST_PC_ISNOT(VOICED) && LAST_PC_ISNOT(GLOTTAL) && LAST_PC_ISNOT(SILENT)
	&& (Last_PC != PC_HH)) Phonet61();

    if THIS_PC_ISNOT(VOWEL) Phonet62();

   /*
    *	Delay onset of voicing after /D/, /G/, and /GX/.  (3/28/91)
    *	Changed	the way AV is done.  Was copied from previous time,
    *	now just set to 0.
    */

    switch(Last_PC)
    {
	case PC_D:
	case PC_GX:
	case PC_G:
	    AV.Cumdur++;    AV.Segdur--;    AV.Mintime++;
	    F1.Cumdur++;    F1.Segdur--;    F1.Mintime++; 
	    F2.Cumdur++;    F2.Segdur--;    F2.Mintime++; 
	    F3.Cumdur++;    F3.Segdur--;    F3.Mintime++; 
	    A1.Cumdur++;    A1.Segdur--;    A1.Mintime++; 
	    A2.Cumdur++;    A2.Segdur--;    A2.Mintime++; 
	    A3.Cumdur++;    A3.Segdur--;    A3.Mintime++; 

	    *(F1.Cumdur - 1) = *(F1.Cumdur - 2);
	    *(F2.Cumdur - 1) = *(F2.Cumdur - 2);
	    *(F3.Cumdur - 1) = *(F3.Cumdur - 2);
	    *(A1.Cumdur - 1) = *(A1.Cumdur - 2);
	    *(A2.Cumdur - 1) = *(A2.Cumdur - 2);
	    *(A3.Cumdur - 1) = *(A3.Cumdur - 2);
	    *(AV.Cumdur - 1) = 0;

	    break;

	default:
	    break;
    }

}  /* end PhonetC6() */

void Phonet60()
{

   /*
    *	C.6.0.1 and C.6.0.2  -- Applies to f4 -- ignored.
    */

   /*
    *	C.6.0.3a and b
    */

    if (THIS_PC_IS(ROUND) && (Last_PC == PC_Y))
      {
	F1.Tcf = 13;
	F2.Tcf = 13;
	F3.Tcf = 13;
	A1.Tcf = 13;
	A2.Tcf = 13;
	A3.Tcf = 13;
	DBG(printf("C.6.0.3a\n"));
      }
    else if LAST_PC_IS(LIQGLIDE)
      {
	F1.Tcf = 9;
	F2.Tcf = 9;
	A1.Tcf = 9;
	A2.Tcf = 9;
	DBG(printf("c.6.0.3b\n"));
      }

    if (LAST_PC_IS(LIQGLIDE) && LAST_PC_IS(RETRO))
      {
	F3.Tcf = 10;
	A3.Tcf = 10;
	DBG(printf("c.6.04\n"));
      }

    if (LAST_PC_IS(WGLIDE) || LAST_PC_IS(YGLIDE))
      {
	F1.Bper = 25;
	F2.Bper = 25;
	F3.Bper = 25;
	A1.Bper = 25;
	A2.Bper = 25;
	A3.Bper = 25;
	DBG(printf("c.6.05\n"));
      }

    if (THIS_PC_IS(ROUND) && LAST_PC_IS(PALATAL))
      {
	F2.Tcf += 5;
	A2.Tcf += 5;
	DBG(printf("c.6.06\n"));
      }

}  /* end Phonet60() */

void Phonet61()
{
LONG	i, delta, incr;

    Aspdur = 5;
    Aspam1 = Aspamp;
    DBG(printf("c.6.1.1 and c.6.1.2\n"));

    if (!Last_PCS)
      {
	Aspdur  = 2;
	Aspam1 -= 3;
	DBG(printf("c.6.1.3\n"));
      }

    if THIS_PC_ISNOT(VOWEL)
      if (THIS_PC_ISNOT(LATERAL) && LAST_PC_ISNOT(LABIAL))
 	{
	  Aspdur = 7;
	  DBG(printf("c.6.1.4a\n"));
        }
      else
	{
	  Aspdur = 6;
	  DBG(printf("c.6.1.4b\n"));
	}

    if ((Old_PCF & VOICED) && !This_PCS)
      {
	Aspdur -= 1;
	DBG(printf("c.6.1.5\n"));
       }

    if ((This_PC == PC_AXP) || (This_PC == PC_QX))
      {
	Aspdur = 8;
	Aspam1 -= 11;
	if LAST_PC_ISNOT(VOICED)   AV.Target = 0;
	DBG(printf("6.1.6\n"));
      }

    if LAST_PC_IS(PLOSIVE)
      {
	Burstdur   >>= 1;
	AV.Cumdur   -= Burstdur;
	AH.Cumdur   -= Burstdur;
	AV.Segdur   += Burstdur;
	AH.Segdur   += Burstdur;
	AV.Mintime  -= Burstdur;
	AH.Mintime  -= Burstdur;
	Aspdur      += Burstdur;
 	DBG(printf("c.6.1.7 adjusting av,ah cumdur,segdur by %ld\n",Burstdur));
      }

    if ((Old_PC == PC_S) && !(Last_bits & SYLLSTART) && LAST_PC_IS(PLOSIVE))
      {
	Aspdur = 0;
    	DBG(printf("c.6.1.7.5  /S/ precedes plos in same syll, Aspdur = 0\n"));
      }

    if LAST_PC_IS(FRICATIVE)
      if THIS_PC_IS(VOWEL)
	{
	  Aspdur = 1;
	  DBG(printf("c.6.1.8\n"));
	}
      else
	{
  	  Aspdur = MIN(AH.Segdur >> 1, 2);	/* was just segdur/2 in book */
	  DBG(printf("c.6.1.9\n"));
	}

    Aspdur  = MIN(MIN(Aspdur,AH.Segdur),AV.Segdur);
    DBG(printf("c.6.1.10 aspdur now %ld\n",Aspdur));

    if (THIS_PC_IS(RETRO) && LAST_PC_IS(ALVEOLAR))
      {
	Aspam1 += 5;
	DBG(printf("c.6.1.11\n"));		/* Changed 3/15/91 was 9 */
      }

    if (Aspdur != 0)
      {
	AH.Segdur  -= Aspdur;			/* Adjust segdurs */
	AV.Segdur  -= Aspdur;
	AH.Mintime  = Aspdur;
	AV.Mintime  = Aspdur;
	while (Aspdur--)
          {
	    *AH.Cumdur++  = Aspam1;
	    *AV.Cumdur++  = 0;
          }
	DBG(printf("c.6.1.12a/b ah.segdur=%d  av.segdur=%d\n",
		AH.Segdur,AV.Segdur));
      }

}

void Phonet62()
{
WORD	temp;

    if (This_PC == PC_L)
      {
	AV.Target -= 3;
	DBG(printf("C.6.2.1\n"));
      }

    if ((This_PC == PC_L) && NEXT_PC_IS(SONORANT) && NEXT_PC_ISNOT(NASAL))
      {
	F2.Target = (29*F2.Target + 3*Parms[Next_PC].f2) >> 5;
	A2.Target = (29*A2.Target + 3*Parms[Next_PC].a2) >> 5;
	DBG(printf("c.6.2.2\n"));
      }

    if (This_PC == PC_RR)
      {
	F3.Target = F2.Target + FADJ(250);
	DBG(printf("c.6.2.3\n"));

	if LAST_PC_IS(LABIAL | DENTAL | PALATAL)
	  {
	    F3.Bper = 90;
	    A3.Bper = 90;
	    DBG(printf("c.6.2.3.1 R before lab|dent|palat set f3.bper=90\n"));
	  }
      }

    if ((This_PC == PC_RR) && NEXT_PC_IS(SONORANT) && NEXT_PC_ISNOT(NASAL))
      {
	F2.Target = (24*F2.Target + 8*Parms[Next_PC].f2) >> 5;
	A2.Target = (24*A2.Target + 8*Parms[Next_PC].a2) >> 5;
	DBG(printf("c.6.2.4\n"));
      }

    if ((This_PC == PC_L) && (NEXT_PC_ISNOT(SONORANT) || NEXT_PC_IS(NASAL)))
      {
	F2.Target = (29*F2.Target + 3*FADJ(1450)) >> 5;
	DBG(printf("c.6.2.5\n"));
      }

    if ((This_PC == PC_RR) && (NEXT_PC_ISNOT(SONORANT) || NEXT_PC_IS(NASAL)))
      {
	F2.Target = (24*F2.Target + 8*Parms[Next_PC].f2) >> 5;
	A2.Target = (24*A2.Target + 8*Parms[Next_PC].a2) >> 5;
	DBG(printf("c.6.2.6\n"));
      }

    if (LAST_PC_ISNOT(NASAL) && LAST_PC_IS(SONORANT) && THIS_PC_IS(LATERAL) &&
	(This_PC != PC_LX))
      {
	F1.Bper = 90;
	F2.Bper = 90;
	F3.Bper = 90;
	A1.Bper = 90;
	A2.Bper = 90;
	A3.Bper = 90;
 	DBG(printf("c.6.2.7\n"));
      }

    if (This_PC == PC_LX)
      {
	F1.Bper = 25;	A1.Bper = 25;
	F2.Bper = 50;	A2.Bper = 50;
	F3.Bper = 50;	A3.Bper = 50;
	DBG(printf("c.6.2.7.5  LX Bper rule, F1=25%, F2,3=50%\n"));
      } 

    if THIS_PC_ISNOT(LIQGLIDE)
      {
	F1.Tcf = 9;
	F2.Tcf = 9;
	F3.Tcf = 9;
	A1.Tcf = 9;
	A2.Tcf = 9;
	A3.Tcf = 9;
	DBG(printf("c.6.2.8.a\n"));
      }
    else if LAST_PC_IS(LIQGLIDE)
      {
	F1.Tcf = 5;
	F2.Tcf = 5;
	F3.Tcf = 5;
	A1.Tcf = 5;
	A2.Tcf = 5;
	A3.Tcf = 5;
	DBG(printf("c.6.2.8.b\n"));
      }
    else
      {
	F1.Tcf = 7;
	F2.Tcf = 7;
	F3.Tcf = 7;
	A1.Tcf = 7;
	A2.Tcf = 7;
	A3.Tcf = 7;
	DBG(printf("c.6.2.8.c\n"));
      }

    if THIS_PC_IS(RETRO)
      {
	F3.Tcf = 9;
	A3.Tcf = 9;
	DBG(printf("c.6.2.9\n"));
      }

    if THIS_PC_IS(LIQGLIDE)
      {
	if LAST_PC_IS(VOWEL)
	  {
	    temp   = This_dur >> 1;
	    F1.Tcf = temp;
	    F2.Tcf = temp;
	    F3.Tcf = temp;
	    A1.Tcf = temp;
	    A2.Tcf = temp;
	    A3.Tcf = temp;
	    DBG(printf("c.6.2.10 this pc liqgli,last pc voicd,tcf=segdur/2\n"));
	  }
      }

    if (THIS_PC_IS(LATERAL) && LAST_PC_IS(STOP) && LAST_PC_IS(LABIAL))
      {
	    F1.Tcf = 1;
	    F2.Tcf = 1;
	    F3.Tcf = 1;
	    A1.Tcf = 1;
	    A2.Tcf = 1;
	    A3.Tcf = 1;
	    DBG(printf("c.6.2.11 labial stop before lateral f1-a3 tcf=1\n"));
      }	

}  /* end phonet62() */

/* ===== phonetc7.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

WORD	F1Diptar;
WORD	F2Diptar;
WORD	F3Diptar;
WORD	A1Diptar;
WORD	A2Diptar;
WORD	A3Diptar;

void PhonetC7(struct narrator_rb * iorb, ULONG centphon, ULONG centpct)
{
	LONG	delta, incr, i;
extern	void	Phonet70();
extern	void	Phonet71();

    DBG(printf("Entering C.7 -- Vowel rules\n"));

   /*
    *  	Setup temp diphthong target values.  Use formant and ampltude 
    *	values from the "This_PC+1" entry of the Parms array.  Note that
    *	This_PC+1 is not equal to Next_PC because Next_PC points to the
    *	phone after the "diphthong prime" entry.
    */

    if THIS_PC_IS(DIPHTHONG)
      {
	F1Diptar = Parms[This_PC+1].f1;
	F2Diptar = Parms[This_PC+1].f2;
	F3Diptar = Parms[This_PC+1].f3;
	A1Diptar = Parms[This_PC+1].a1;
	A2Diptar = Parms[This_PC+1].a2;
	A3Diptar = Parms[This_PC+1].a3;
	DBG(printf("initializing temp f1..f3  a1..a3 diptars\n"));
      }

			     Phonet70(iorb, centphon, centpct);
    if THIS_PC_IS(DIPHTHONG) Phonet71(iorb);

}

void Phonet70(struct narrator_rb * iorb, ULONG centphon, ULONG centpct)
{

    if ((This_PC == PC_AXP) && (Old_PCF & SONORANT) && 
	((Old_PCF & NASAL) ? 0 : 1))
      {
	F2.Target = (F2.Target + Parms[Old_PC].f2) >> 1;
	A2.Target = (A2.Target + Parms[Old_PC].a2) >> 1;
	DBG(printf("rule 7.01: new f2,a2 targs = %d  %d\n",
		F2.Target,A2.Target));
      }

    if (THIS_PC_IS(FRONT) && THIS_PC_IS(LAX) && NEXT_PC_IS(VELAR))
      {
	F2Diptar = F2.Target;
	A2Diptar = A2.Target;
	DBG(printf("rule 7.02\n"));
      }

    if ((THIS_PC_IS(FRONT) || THIS_PC_IS(YGLIDE)) && NEXT_PC_IS(LATERAL))
      {
	if(Next_PC == PC_LX)
	  {
	    F2Diptar = (F2Diptar + Parms[PC_LX].f2) >> 1;
	    A2Diptar = (A2Diptar + Parms[PC_LX].a2) >> 1;
	  }
	else  F2Diptar -= FADJ(300);
	DBG(printf("rule 7.03\n"));

	if THIS_PC_ISNOT(DIPHTHONG)
	  {
	    if(Next_PC == PC_LX)
	      {
	        F2.Target = (F2.Target + (UWORD)Parms[PC_LX].f2) >> 1;
	        A2.Target = (A2.Target +  (WORD)Parms[PC_LX].a2) >> 1;
	      }
	    else  F2.Target -= FADJ(300);
	    DBG(printf("rule 7.04 \n"));
	  }
      }

    if ((This_PC == PC_YU) && NEXT_PC_IS(ALVEOLAR) && NEXT_PC_IS(PLOSIVE))
      {
	F2Diptar += FADJ(200);
	DBG(printf("rule 7.05\n"));
      }

    if (LAST_PC_IS(F2BACK) && THIS_PC_IS(ROUND))
      {
	F2.Tcf += 5;
	A2.Tcf += 5;
	DBG(printf("rule 7.06\n"));
      }

    if (THIS_PC_IS(YGLIDE) && NEXT_PC_IS(ALVEOLAR))
      {
	F2Diptar -= FADJ(150);
	DBG(printf("rule 7.07\n"));
      }

/*	rule 7.08 not included 	*/

    if THIS_PC_IS(SCHWA)
      {
	F3.Target = (F3.Oldval + F3.Target + (UWORD)Parms[Next_PC].f3)/3;
	A3.Target = (A3.Oldval + A3.Target +  (WORD)Parms[Next_PC].a3)/3;
	DBG(printf("rule 7.09 \n"));
      }

    if THIS_PC_IS(F2BACK)
      {
	F2.Tcf -= 2;
	A2.Tcf -= 2;
	DBG(printf("rule 7.010\n"));
      }

    if NEXT_PC_IS(NASAL)
      if THIS_PC_IS(DIPHTHONG)
	{
	  F1Diptar  = (F1Diptar + FADJ(500)) >> 1;
	  A1Diptar -= 4;
	  DBG(printf("rule 7.011a vowel nasalztn F1Diptar=%ld  A1Diptar=%ld\n",
	         (LONG)F1Diptar, (LONG)A1Diptar));
	}
      else
	{
	  F1.Target  = (F1.Target + FADJ(500)) >> 1;
	  A1.Target -= 4;
	  DBG(printf("rule  7.011b (vowel nasalztn) F1targ=%ld  A1targ=%ld\n",
		(LONG)F1.Target, (LONG)A1.Target));
	}

    if LAST_PC_IS(LATERAL)
      {
	A1.Bper = 75;
	A2.Bper = 75;
	A3.Bper = 75;
	DBG(printf("rule 7.012  Lateral precedes vowel: Bper[a1..a3] = 75"));
      }

/* == Centralization ==
   Shifts f1..a3 and diphthong targets towards a certain user specified
   phoneme by a fixed user specified percentage
*/
	if((iorb->flags & NDF_NEWIORB) && (centpct > 0))
	{
	  F1.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].f1-F1.Target));
	  F2.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].f2-F2.Target));
	  F3.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].f3-F3.Target));
	  A1.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].a1-A1.Target));
	  A2.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].a2-A2.Target));
	  A3.Target += PCT((WORD)centpct, ((WORD)Parms[centphon].a3-A3.Target));
	  F1Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].f1-F1Diptar));
	  F2Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].f2-F2Diptar));
	  F3Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].f3-F3Diptar));
	  A1Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].a1-A1Diptar));
	  A2Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].a2-A2Diptar));
	  A3Diptar  += PCT((WORD)centpct, ((WORD)Parms[centphon].a3-A3Diptar));
	}
} /* end Phonet70() */

void Phonet71(struct narrator_rb * iorb)
{
	LONG	i;
	UWORD	Tcdiph, Tdmid;
	UWORD	F1Tcenter, F2Tcenter, F3Tcenter;
	UWORD	F1Tcdips,  F2Tcdips,  F3Tcdips;
	UWORD	A1Tcenter, A2Tcenter, A3Tcenter;
	UWORD	A1Tcdips,  A2Tcdips,  A3Tcdips;
	UWORD	artic;				/* local articulation coef */
extern	void	DrawDiphTrans();

    for (i = 0; i < NUMDIPHTRANS; ++i) if (Diphtran[i][0] == This_PC) break;
    Tcdiph = Diphtran[i][1];
    Tdmid  = Diphtran[i][2];
    DBG(printf("rule 7.1.1 Tcdiph=%ld Tdmid=%ld\n", (LONG)Tcdiph, (LONG)Tdmid));

    F1Tcenter = (Tdmid*F1.Segdur)/100;		/* Tdmid is a percentage */
    F2Tcenter = F1Tcenter;
    F3Tcenter = F1Tcenter;
    A1Tcenter = F1Tcenter;
    A2Tcenter = F1Tcenter;
    A3Tcenter = F1Tcenter;

    DBG(printf("rule 7.1.2:  Tcenter=%d \n",F1Tcenter));

/*  Tcdips   = Tcdiph * .5 * (1 + Segdur[f1] / 225ms)		*/
/*    F1Tcdips = (Tcdiph * (64 + (F1.Segdur << 6) / 27)) >> 7; */
    F1Tcdips = (Tcdiph * (F1.Segdur << 6) / 27) >> 7;
    F2Tcdips = F1Tcdips;
    F3Tcdips = F1Tcdips;
    A1Tcdips = F1Tcdips;
    A2Tcdips = F1Tcdips;
    A3Tcdips = F1Tcdips;

    DBG(printf("rule 7.1.3:  Tcdips = %d\n",F1Tcdips));

    if ((Last_PC == PC_HH) && THIS_PC_ISNOT(LAX))
      {
	F1Tcenter = (21*F1Tcenter) >> 5;
	F2Tcenter = F1Tcenter;
	F3Tcenter = F1Tcenter;
	A1Tcenter = F1Tcenter;
	A2Tcenter = F1Tcenter;
	A3Tcenter = F1Tcenter;
	DBG(printf("rule 7.1.4:  Tcenter = %d\n",F1Tcenter));
      }

    F1.Bvf = (F1.Target + F1Diptar) >> 1;
    F2.Bvf = (F2.Target + F2Diptar) >> 1;
    F3.Bvf = (F3.Target + F3Diptar) >> 1;
    A1.Bvf = (A1.Target + A1Diptar) >> 1;
    A2.Bvf = (A2.Target + A2Diptar) >> 1;
    A3.Bvf = (A3.Target + A3Diptar) >> 1;
    DBG(printf("rule 7.1.5:  f1-f3 Bvf = %d   %d   %d\n",F1.Bvf,F2.Bvf,F3.Bvf));
    DBG(printf("             a1-a3 Bvf = %d   %d   %d\n",A1.Bvf,A2.Bvf,A3.Bvf));

    if (This_PC == PC_OY)
      {
	F1.Bvf += FADJ(70);
	DBG(printf("rule 7.1.6:  f1 bvf = %d\n",F1.Bvf));
      }

    if ((This_PC == PC_OY) || (This_PC == PC_AY))
      {
	F2.Bvf += FADJ(200);
	F3.Bvf -= FADJ(200);
	DBG(printf("rule 7.1.7 and 7.1.8: F2 bvf = %d  F3 bvf = %d\n",
		F2.Bvf, F3.Bvf));
      }

    if (This_PC == PC_YU)
      {
	F3Tcenter = (10*F3Tcenter) >> 5;
	A3Tcenter = (10*A3Tcenter) >> 5;
 	DBG(printf("rule 7.1.9:  A3,F3 Tcenter = %d   %d\n",F3Tcenter,A3Tcenter));
      }
/*
    else if ((This_PC == PC_EXR) || (This_PC == PC_IXR))
      {
	F3Tcenter = (19*F3Tcenter) >> 5;
	A3Tcenter = (19*A3Tcenter) >> 5;
	DBG(printf("rule 7.1.10:  A3,F3 Tcenter = %d  %d\n",F3Tcenter,A3Tcenter));
      }
*/

    F1.Bvb = F1.Bvf;
    F2.Bvb = F2.Bvf;
    F3.Bvb = F3.Bvf;
    A1.Bvb = A1.Bvf;
    A2.Bvb = A2.Bvf;
    A3.Bvb = A3.Bvf;
    DBG(printf("rule 7.1.11:   Bvb's set to Bvf's\n"));

   /*
    *	Articulation of diphthongs.
    *   Smoothing adjusted according to user specified percentage
    */

    if((iorb->flags & NDF_NEWIORB) && (iorb->articulate != 100))
    {
	artic = (UWORD)iorb->articulate;
	F1Tcdips = PCT(artic, F1Tcdips);
	F2Tcdips = PCT(artic, F2Tcdips);
	F3Tcdips = PCT(artic, F3Tcdips);
	A1Tcdips = PCT(artic, A1Tcdips);
	A2Tcdips = PCT(artic, A2Tcdips);
	A3Tcdips = PCT(artic, A3Tcdips);
	DBG(printf("Adjusting Tcdips for articulation, artic=%d\n",artic));
    }

    DrawDiphTrans("F1", &F1, F1Tcenter, F1Diptar, F1Tcdips);
    DrawDiphTrans("F2", &F2, F2Tcenter, F2Diptar, F2Tcdips);
    DrawDiphTrans("F3", &F3, F3Tcenter, F3Diptar, F3Tcdips);
    DrawDiphTrans("A1", &A1, A1Tcenter, A1Diptar, A1Tcdips);
    DrawDiphTrans("A2", &A2, A2Tcenter, A2Diptar, A2Tcdips);
    DrawDiphTrans("A3", &A3, A3Tcenter, A3Diptar, A3Tcdips);
    
    DBG(printf("rule 7.1.12:  draw diphthong tracks\n"));

}

void DrawDiphTrans(char * DebugString, struct 	PhonetParms * Track, UWORD Tcenter, WORD Diptar, UWORD Tcdips)
{
extern	void	 PhonetInterp();
	WORD	*cumdur;
	WORD	 target;
	WORD	 oldval;
	UWORD	 mid;
	WORD	 bvb;
	WORD	 bvf;
	UBYTE	 segdur;
	UBYTE	 olddur;
	BYTE	 tcb;
	BYTE	 tcf;
	WORD	 start, incr;
	WORD	 i,j;

    DBG(printf("interpolating diphthong track %s\n",DebugString));
    DBG(printf("    target = %d   diptar = %d\n",Track->Target,Diptar));
    
    cumdur = Track->Cumdur;
    target = Track->Target;
    oldval = Track->Oldval;
    segdur = Track->Segdur;
    olddur = Track->Olddur;
    bvb    = Track->Bvb;
    bvf	   = Track->Bvf;

    for (mid = 0; mid < Tcenter;         mid++) *cumdur++ = target;
    for (mid = 0; mid < segdur-Tcenter;  mid++) *cumdur++ = Diptar;
    cumdur -= segdur - Tcenter;

    if ((tcb = MIN(Tcdips, Tcenter-1)) > 0)
      {
 	start  = *(cumdur - (tcb + 1)) << 5;
	incr   = ((bvb << 5) - start)/tcb;
	cumdur = cumdur - (LONG)tcb;
	while (tcb--)
	  {
	    start     += incr;
	    *cumdur++  = (start >= 0) ?  ( start + 16) >> 5 :
	  			       -((-start + 16) >> 5);
      	  }
      }

    if ((tcf = MIN(Tcdips, segdur-Tcenter-1)) > 0)
      {
	incr   = ((*(cumdur+tcf) - *(cumdur-1)) << 5)/tcf;   /*cumdur+tcf-1 */
	start  = (*(cumdur-1) << 5) + incr;
	while (tcf--)
	  {
	    *cumdur++  = (start >= 0) ?   ( start + 16) >> 5 :
			 		-((-start + 16) >> 5);
	    start    += incr;
	  }
      }
}

/* ===== phonetc8.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

void PhonetC8()
{
extern	void	Phonet80();
extern	void	Phonet81();
extern	void	Phonet82();
extern	void	Phonet83();
extern	void	Phonet84();

    DBG(printf("Entering C.8 -- Obstruent rules\n"));

   /*
    *  Well, there don't seem to be any C.8 rules.  Guess we will just
    *  skip on to the C.8.1 rules
    */

    if (THIS_PC_IS(PLOSIVE) || THIS_PC_IS(FRICATIVE)) Phonet81();
    if THIS_PC_IS(FRICATIVE)			      Phonet82();
    if THIS_PC_IS(STOP)				      Phonet83();
    if THIS_PC_IS(NASAL)			      Phonet84();
	
}

void Phonet81()
{

    DBG(printf("rule 8.1.1: zarfed\n"));

    if (THIS_PC_IS(VELAR) && NEXT_PC_ISNOT(VOWEL))
      {
	Buramp -= 5;
	DBG(printf("rule c.8.1.5\n"));
      }

    if ((LAST_PC_ISNOT(VOICED) || LAST_PC_ISNOT(SONORANT))
	&& THIS_PC_IS(VOICED) && THIS_PC_IS(PLOSIVE))
      {
	AV.Target = 0;
	DBG(printf("rule 8.1.6 av.target = 0\n"));
      }

}

void Phonet82()
{

    if NEXT_PC_IS(SILENT)
      {
	AF.Target -= 4;
	DBG(printf("rule c.8.2.1:  new af.target=%ld\n",(LONG)AF.Target));
      }

/*	removed 8/16/88 af now adjusted in c10 rules
    if (LAST_PC_ISNOT(FRICATIVE) && LAST_PC_ISNOT(STOP) && NEXT_PC_IS(VOWEL))
      if (AF.Segdur < 10)
 	{
	  AF.Target += (10 - AF.Segdur)*AF.Target/AF.Segdur;
	  DBG(printf("rule c.8.2.2: short fric adj af.tar now=%d\n",AF.Target));
	}
*/

    if (LAST_PC_IS(VOWEL) && THIS_PC_IS(VOICED) && NEXT_PC_IS(VOWEL))
      {
	AV.Target += 3;
	DBG(printf("rule 8.2.3: av.target increase by 3 to %ld\n",AV.Target));
      }

    if (THIS_PC_IS(PALATAL) && NEXT_PC_IS(VOWEL) && NEXT_PC_IS(ROUND))
      {
	F2.Target -= FADJ(50);
	F3.Target -= FADJ(300);
	DBG(printf("rule c.8.2.4:\n   new f2.target=%ld  f3.target=%ld\n",
		(LONG)F2.Target, (LONG)F3.Target));
      }

}

void Phonet83()
{
LONG	oldAF, incr, i;
WORD	tempdur, temp;

    if LAST_PC_ISNOT(STOP)
      {
	AV.Trantype = SMODIS;
	AF.Trantype = SMODIS;
	AH.Trantype = SMODIS;
	F1.Trantype = SMODIS;
	A1.Trantype = SMODIS;
	F2.Trantype = SETSMO;
	F3.Trantype = SETSMO;
	A2.Trantype = SETSMO;
	A3.Trantype = SETSMO;
	DBG(printf("rule 8.3.1:\n  av,af,ah,f1,a1 trantypes now smodis\n"));
	DBG(printf("             f2,f3,a2,a3 trantypes now setsmo\n"));
      }

    if LAST_PC_IS(HIGH)
      {
	F1.Tcf = 2;
	F2.Tcf = 1;
	F3.Tcf = 1;
	A1.Tcf = 2;
	A2.Tcf = 1;
	A3.Tcf = 1;
	DBG(printf("rule 8.3.0.2"));
      }
    else
      {
	for (i = 0;  i < NUMTCOBSTS;  ++i) if (Tcobst[i][0] == This_PC) break;
	temp   = Tcobst[i][1];
	F1.Tcf = (temp + 2) >> 1;
	F2.Tcf = temp;
	F3.Tcf = temp;
	A1.Tcf = (temp + 2) >> 1;
	A2.Tcf = temp;
	A3.Tcf = temp;
	DBG(printf("rule 8.3.3\n  f1,a1 tcf=%d   f2,f3,a2,a3 tcf=%d\n",
		(WORD)F1.Tcf, (WORD)F2.Tcf));
      }

   /*
    *	C.8.3.1 rules
    */

    if (THIS_PC_IS(AFFRICATE) || (This_PC == PC_DX) ||
	(THIS_PC_IS(PLOSIVE) && 
	(NEXT_PC_ISNOT(SILENT) || NEXT_PC_IS(NASAL))))
/*	(NEXT_PC_ISNOT(STOP) && NEXT_PC_ISNOT(SILENT) || NEXT_PC_IS(NASAL)))) */
      {
	for (i = 0; i < NUMBURDURS; ++i) if (This_PC == Burdur[i][0]) break;
	Burstdur = Burdur[i][1];
	DBG(printf("rule c.8.3.1.1:\n  burstdur=%ld\n", (LONG)Burstdur));

	if ((This_PC == PC_T) && NEXT_PC_IS(RETRO))
	  {
	    Burstdur += 1;
	    DBG(printf("rule c.8.3.1.2:\n  burstdur=%ld\n", (LONG)Burstdur));
	  }

	if (THIS_PC_IS(AFFRICATE) && This_PCS && Next_PC != PC_RR)
	  {
	    if (This_PC == PC_J) Burstdur = 8;
	    else Burstdur = 12;
	    DBG(printf("rule c.8.3.1.2.5 stressed j/ch burstdur=70/100msec\n"));
	  }

	if((Last_PC == PC_S) && (Last_bits & SYLLSTART))
	  {
	    Burstdur = 2;
	    DBG(printf("ad hoc: /S/ precedes plos in same syll: Burstdur=2\n"));
	  }

	Burstdur = MIN(Burstdur, AF.Segdur);
	DBG(printf("rule c.8.3.1.3:\n  burstdur=%ld\n", (LONG)Burstdur));

	Burstdur = MAX(Burstdur, 1);
        DBG(printf("rule c.8.3.1.4:\n  burstdur=%ld\n", (LONG)Burstdur));

	if (*(AF.Cumdur-1) != 0)
	  {
	    *--AF.Cumdur -= 20;				/* shoud dbl check */
	    oldAF       = *(AF.Cumdur - 3) << 5;
	    incr        = ((*AF.Cumdur << 5) - oldAF)/3;
	    AF.Cumdur  -= 2;
	    for (i=0; i<3; ++i)
	      {
	    	oldAF	     += incr;
	    	*AF.Cumdur++  = oldAF >> 5;
	      }
	    DBG(printf("rule c.8.3.1.5:    smoothed back 30 msec in af\n"));
	  }

	tempdur = AF.Segdur - Burstdur;
	AF.Mintime = tempdur;
	DBG(i = tempdur);
	while (tempdur--) *AF.Cumdur++  = 0;
	AF.Segdur = Burstdur;
	DBG(printf("rule c.8.3.1.6:   drew af seg of 0 for dur=%ld\n",
		(LONG)(i)));

	if THIS_PC_ISNOT(VOICED)
	  {
	    Buramp += 6;
	    DBG(printf("rule c.8.3.1.7:   new Buramp=%ld\n",(LONG)Buramp));
	  }

	if NEXT_PC_IS(STOP)
	  {
	    Buramp -= 3;
	    DBG(printf("c.8.3.1.7.5 ad hoc: nxt pc stop,buramp-3=%d\n",Buramp));
	  }

	if (LAST_PC_IS(NASAL) && !This_PCS)
	  {
	    Buramp -= 6;
/*	    if(This_bits & PHRASEFINAL)  Buramp -= 3; */
	    DBG(printf("rule c.8.3.1.8:   new Buramp=%ld\n",(LONG)Buramp));
	  }

	if (LAST_PC_ISNOT(NASAL) && !This_PCS)
	  {
	    Buramp -= 3;
/*	    if(This_bits & PHRASEFINAL)  Buramp -= 3; */
	    DBG(printf("rule c.8.3.1.9:   new Buramp=%ld\n",(LONG)Buramp));
	  }

	if ((Next_PC == PC_AXP) || NEXT_PC_IS(FRICATIVE))
	  {
	    Buramp -= 3;
	    DBG(printf("rule c.8.3.1.10:   new Buramp=%ld\n",(LONG)Buramp));
	  }

	if((Last_PC == PC_S) && (Last_bits & SYLLSTART))
	  {
	    Buramp -= 5;
	    DBG(printf("ad hoc: /S/ precedes plos in same syll: Buramp -=5\n"));
	  }

	AF.Target = Buramp;
	DBG(printf("rule c.8.3.1.11:  AF target = %ld\n",Buramp));

	AF.Trantype = DISCON;
	DBG(printf("rule c.8.3.1.12:  af trantype now discon\n"));

      }					/* end of c.8.3.1 rules */

}

void Phonet84()
{

    if THIS_PC_ISNOT(SYLLABIC)
      {
	AF.Trantype = SMODIS;
	AH.Trantype = SMODIS;
	F1.Trantype = SMODIS;
	F2.Trantype = SMODIS;
	F3.Trantype = SMODIS;
	A1.Trantype = SMODIS;
	A2.Trantype = SMODIS;
	A3.Trantype = SMODIS;
	DBG(printf("rule c.8.4.2:    af..a3 trantypes now smodis\n"));

	AV.Trantype = DISCON;
	DBG(printf("rule c.8.4.4:    av trantype now discon\n"));
      }

    if LAST_PC_ISNOT(VOICED)
      {
	AV.Trantype = DISSMO;
	DBG(printf("rule c.8.4.5:    av trantype now dissmo\n"));
      }

}
    

/* ===== phonetc9.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

BOOL	MannerSwap;

void PhonetC9()
{
UBYTE	Temp_PC;			/* Temp storage of PC		*/
ULONG	Temp_PCF;			/* Temp PC features		*/
UBYTE	Temp_PCS;			/* Temp PC stress		*/

UBYTE	Prev_PC;			/* Save last PC			*/
ULONG	Prev_PCF;			/*      last PC features	*/
UBYTE	Prev_PCS;			/* 	last PC stress		*/

UBYTE	Curr_PC;			/* Save current PC		*/
ULONG	Curr_PCF;			/*	current PC features	*/
UBYTE	Curr_PCS;			/* 	current PC stress	*/

WORD	temp;

extern	void	Phonet91();
extern	void	Phonet92();

    DBG(printf("Entering C.9 -- Adjustments\n"));

    MannerSwap = FALSE;
    if (Manner > PrevManner)
      {
	Prev_PC  = Last_PC;			/* Save previous PC	   */
	Curr_PC  = This_PC;			/* Save current PC	   */
	Temp_PC  = This_PC;			/* Swap curr and prev PC's */
	This_PC  = Last_PC;
	Last_PC  = Temp_PC;

	Prev_PCF = Last_PCF;			/* Save previous PCF	   */
	Curr_PCF = This_PCF;			/* Save current PCF        */
	Temp_PCF = This_PCF;			/* Swap cur and prev PCF's */
	This_PCF = Last_PCF;
	Last_PCF = Temp_PCF;

	Prev_PCS = Last_PCS;			/* Save previous PCS	   */
	Curr_PCS = This_PCS;			/* Save current PCS   	   */
	Temp_PCS = This_PCS;			/* Swap cur and prev PCS's */
	This_PCS = Last_PCS;
	Last_PCS = Temp_PCS;

	temp = F1.Target;    F1.Target = F1.Oldval;    F1.Oldval = temp;
	temp = F2.Target;    F2.Target = F2.Oldval;    F2.Oldval = temp;
	temp = F3.Target;    F3.Target = F3.Oldval;    F3.Oldval = temp;
	temp = A1.Target;    A1.Target = A1.Oldval;    A1.Oldval = temp;
	temp = A2.Target;    A2.Target = A2.Oldval;    A2.Oldval = temp;
	temp = A3.Target;    A3.Target = A3.Oldval;    A3.Oldval = temp;

	MannerSwap = TRUE;
	DBG(printf("rule c.9.1 swapping current and prev segments\n"));
      }

    if THIS_PC_IS(RETRO)
      {
	F2.Bper = 75;
	F3.Bper = 75;
	A2.Bper = 75;
	A3.Bper = 75;
	DBG(printf("rule 9.2: bper[f2..a3] <-- 75 / [+retro]\n"));
	DBG(printf("                                [  --- ]\n\n"));
      }

    if (LAST_PC_IS(PALATAL) && LAST_PC_ISNOT(SONORANT))
      {
	F2.Bper  = 20;
	A2.Bper  = 20;

	F2.Tcf  += 3;
	A2.Tcf  += 3;
	DBG(printf("rule 9.3: Bper[f2,a2]<--20, Tcf^30/ [+pal,-son] --- \n"));
	DBG(printf("                                    [    S    ]\n\n"));
      }

    if (LAST_PC_IS(STOP) && THIS_PC_ISNOT(STOP) && LAST_PC_ISNOT(AFFRICATE)
	&& (Last_PC != PC_DX))   Phonet91();

    if (MannerSwap)
      {
	Last_PC  = Prev_PC;			/* Restore swapped segments  */
	Last_PCF = Prev_PCF;
	Last_PCS = Prev_PCS;

	This_PC  = Curr_PC;
	This_PCF = Curr_PCF;
	This_PCS = Curr_PCS;

	temp = F1.Target;    F1.Target = F1.Oldval;    F1.Oldval = temp;
	temp = F2.Target;    F2.Target = F2.Oldval;    F2.Oldval = temp;
	temp = F3.Target;    F3.Target = F3.Oldval;    F3.Oldval = temp;
	temp = A1.Target;    A1.Target = A1.Oldval;    A1.Oldval = temp;
	temp = A2.Target;    A2.Target = A2.Oldval;    A2.Oldval = temp;
	temp = A3.Target;    A3.Target = A3.Oldval;    A3.Oldval = temp;

   /*
    *	Complement percentages to account for target swapping
    */

	F1.Bper = 100 - F1.Bper;
	F2.Bper = 100 - F2.Bper;
	F3.Bper = 100 - F3.Bper;
	A1.Bper = 100 - A1.Bper;
	A2.Bper = 100 - A2.Bper;
	A3.Bper = 100 - A3.Bper;

	DBG(printf("restoring swapped segments at end of C.9 rules\n"));
      }

    if (LAST_PC_IS(RGLIDE) && THIS_PC_IS(STOP) && THIS_PC_IS(VELAR))
      {
	F2.Oldval = FADJ(1400);
	F3.Oldval = FADJ(1600);
	DBG(printf("ad hoc: rglide after velar stop,F2,3.Oldval =1400,1600\n"));
      }

    Phonet92();

}

void Phonet91()
{
    F1.Bper = 50;
    A1.Bper = 50;

    F2.Bper = 0;
    A2.Bper = 0;

    F3.Bper = 0;
    A3.Bper = 0;

    DBG(printf("rule 9.1.1: Bper[f1,a1] <-- 50\n\n"));
    DBG(printf("rule 9.1.2: Bper[f2,a2] <--  0\n\n"));
    DBG(printf("rule 9.1.3: Bper[f3,a3] <--  0\n\n"));

    if LAST_PC_IS(NASAL)
      {
	F1.Bper = 0;
	A1.Bper = 0;
	DBG(printf("rule 9.1.4: Bper[f1,a1] <-- 0 / [+nasal] --- \n"));
	DBG(printf("                                [   S  ]\n\n"));
      }

    if (LAST_PC_IS(LABIAL) && THIS_PC_ISNOT(GLOTTAL))
      {
	if THIS_PC_IS(FRONT)
	  {
	    F2.Bper = 65;
	    F3.Bper = 20;
	    A2.Bper = 65;
	    A3.Bper = 20;
	    DBG(printf("rule 9.1.5:\n"));
	  }
        else
          {
	    F2.Bper = 20;
	    F3.Bper = 70;
	    A2.Bper = 20;
	    A3.Bper = 70;
 	    DBG(printf("rule 9.1.6\n"));
	  }

        if THIS_PC_IS(RETRO)
	  {
	    F3.Oldval = FADJ(1750);
	    F3.Bper   = 20;
	    A3.Bper   = 20;
	    DBG(printf("rule 9.1.7\n"));
	  }

      }

    if (LAST_PC_IS(ALVEOLAR) && THIS_PC_IS(LATERAL))
      {
	F2.Oldval = FADJ(1050);
	DBG(printf("rule 9.1.8\n"));
      }

    if ((Last_PC == PC_N) && THIS_PC_ISNOT(LATERAL))
    {      
	if(THIS_PC_IS(ROUND) && MannerSwap)	/* eg /UW N/ */
	{
	    F2.Bper = 50;
	    A2.Bper = 50;
	}	
	else F2.Oldval = FADJ(1600);		/* was 1400 */
	DBG(printf("rule 9.1.9\n"));
    }	

    if (LAST_PC_IS(ALVEOLAR) && (Last_PC != PC_N) && (Last_PC != PC_DX) &&
	THIS_PC_ISNOT(LATERAL))
      {
	F2.Oldval = FADJ(1700);
	A2.Oldval = Parms[Last_PC].a2;
	if THIS_PC_IS(FRONT)  F2.Oldval += FADJ(150);
	DBG(printf("rule 9.1.10\n"));
      }

    if (LAST_PC_IS(ALVEOLAR) && THIS_PC_IS(RETRO))
      {
	F3.Oldval = FADJ(2300);
	DBG(printf("rule 9.1.11\n"));
      }

    if (LAST_PC_IS(ALVEOLAR) && THIS_PC_ISNOT(RETRO))
      {
	F3.Oldval = FADJ(2620);
	DBG(printf("rule 9.1.12\n"));
      }

    if LAST_PC_IS(VELAR)
      {
	F2.Oldval = F2.Target + F1.Target - FADJ(300);
	DBG(printf("rule 9.1.13\n"));
      }

    if LAST_PC_IS(VELAR)
      if THIS_PC_IS(LABIAL)
	{
	  F3.Oldval = F2.Oldval + FADJ(800);
	  DBG(printf("rule 9.1.14\n"));
        }
      else
        {
	  F3.Oldval = F2.Oldval + FADJ(400);
          DBG(printf("rule 9.1.15\n"));
        }

/*
    if (LAST_PC_IS(VELAR) && THIS_PC_IS(FRONT))
      {
	F2.Oldval = Parms[PC_K].f2;
	A2.Oldval = Parms[PC_K].a2;
	DBG(printf("rule 9.1.16 use KP targets \n"));
      }

    if LAST_PC_IS(VELAR)
      {
	if (!MannerSwap)
	  {
	    F3.Oldval = F3.Target;
	    A3.Oldval = A3.Target;
	  }
	DBG(printf("rule 9.1.17 set F3,A3 boundary for velars at target\n"));
      }	
*/

/* Boundary is 50% going into unvoiced velar stop

    if(MannerSwap && LAST_PC_IS(VELAR) && LAST_PC_ISNOT(VOICED))
      {
	F2.Oldval = (Oldval_f2 + F2.Oldval) >> 1;
	F3.Oldval = (Oldval_f3 + F3.Oldval) >> 1;
	A2.Oldval = (Oldval_a2 + A2.Oldval) >> 1;
	A3.Oldval = (Oldval_a3 + A3.Oldval) >> 1;
      }
*/

    if (Last_PC == PC_NX)
      {
	F2.Oldval = (F2.Oldval + F2.Target) >> 1;
	F3.Oldval = (F3.Oldval + F3.Target) >> 1;
	A2.Oldval = (A2.Oldval + A2.Target) >> 1;
	A3.Oldval = (A3.Oldval + A3.Target) >> 1;
	DBG(printf("rule 9.1.17\n"));
      }

    if (LAST_PC_IS(VELAR) && ((This_PC == PC_IY) || (This_PC == PC_IH)))
      {
	F2.Oldval += FADJ(250);
	F3.Oldval += FADJ(50);
	DBG(printf("rule 9.1.18: F2.Oldval up 250, F3.Oldval up 50 \n"));
      }

}

void Phonet92()
{

    if (LAST_PC_IS(ALVEOLAR) && LAST_PC_IS(STOP) && (This_PC == PC_W))
      {
	F2.Oldval = FADJ(1200);
	F3.Oldval = FADJ(2050);
	DBG(printf("rule 9.2.1\n"));
      }

    if (LAST_PC_IS(RGLIDE) || LAST_PC_IS(RETRO))
      if THIS_PC_IS(ALVEOLAR)
        {
	  F2.Target = FADJ(1850);
	  F3.Target = FADJ(2200);
  	  DBG(printf("rule 9.2.2\n"));
        }
      else if THIS_PC_IS(VELAR)
	{
	  F2.Target = FADJ(1700);
	  F3.Target = FADJ(1900);
	  DBG(printf("rule 9.2.3\n"));
	}

    if (LAST_PC_IS(VELAR) && THIS_PC_IS(RETRO))
      {
	F2.Oldval = FADJ(1100);
	F3.Oldval = FADJ(1500);
	DBG(printf("rule 9.2.4\n"));
      }

    if (LAST_PC_IS(ALVEOLAR) && THIS_PC_IS(RETRO))
      {
	F3.Oldval = FADJ(2100);
	DBG(printf("rule 9.2.5\n"));
      }

    if (LAST_PC_IS(LABIAL) && THIS_PC_IS(RETRO))
      {
	F3.Oldval = FADJ(1700);
	DBG(printf("rule 9.2.6\n"));
      }

    if THIS_PC_IS(VELAR)
      if LAST_PC_IS(WGLIDE)
        {
	  F2.Target = FADJ(900);
	  F3.Target = FADJ(2000);
	  DBG(printf("rule 9.2.7a\n"));
        }
/*
      else if (LAST_PC_ISNOT(RGLIDE) && LAST_PC_ISNOT(RETRO))
      	{
	  F2.Target = FADJ(1900);
	  DBG(printf("rule 9.2.7b\n"));
        }
*/

    if (LAST_PC_IS(ALVEOLAR) && LAST_PC_IS(STOP) && THIS_PC_IS(F2BACK))
      {
	F2.Oldval = FADJ(1850);
	DBG(printf("rule 9.2.8\n"));
      }

}


/* ===== phonetc10.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

void PhonetC10(struct narrator_rb * iorb)
{

WORD temp;
UWORD utemp;

extern void PhonetC101();

    /* Obstruent tests with segment reversal */
    if (THIS_PC_ISNOT(SONORANT) || THIS_PC_IS(NASAL|GLOTTAL) ||
	This_PC == PC_UL)  PhonetC101(Last_PC, This_PC, FALSE);

    else if (LAST_PC_ISNOT(SONORANT) || LAST_PC_IS(NASAL|GLOTTAL) ||
	     Last_PC == PC_UL)  PhonetC101(This_PC, Last_PC, TRUE);

   /*
    *  (C.10 Modifications)
    */

    if (!This_PCS)
      {
	AV.Target -= 2;
	DBG(printf("rule 10.01: PC not stressed reduce AV targ by 2 now =%d\n",
		AV.Target));
      }

    if (THIS_PC_IS(PLOSIVE) && THIS_PC_IS(VOICED) &&
	(LAST_PC_ISNOT(VOICED) || LAST_PC_ISNOT(SONORANT)))
      {
	AV.Target = 0;
	DBG(printf("c10: voiced plos preceded by non-sonor, AV.Target=0\n"));
      }

    /*  C.10.1  -- Target[f1..f3] <- avg(Target,Oldval,Nextar)/[+DX] */

    if (This_PC == PC_DX)
      {
	F1.Target = (F1.Target + F1.Oldval + Parms[Next_PC].f1) / 3;
	utemp = ((UWORD)F2.Target<<1)+(UWORD)F2.Oldval+(UWORD)Parms[Next_PC].f2;
	F2.Target = utemp >> 2; 
	F3.Target = (F3.Target + F3.Oldval + Parms[Next_PC].f3) / 3;
	A1.Target = (A1.Target + A1.Oldval + Parms[Next_PC].a1) / 3;
	temp = ((WORD)A2.Target<<1)+(WORD)A2.Oldval+(WORD)Parms[Next_PC].a2;
	A2.Target = temp >> 2;
	A3.Target = (A3.Target + A3.Oldval + Parms[Next_PC].a3) / 3;
	DBG(printf("C.10.1   F2[DX] is now double weighted\n"));
      }
 
/*** SPECIAL CASE SPECIFIC CODE ***/

    if (THIS_PC_IS(DENTAL) && LAST_PC_IS(VOWEL))
    {
	F3.Bper = 100;
	A3.Bper = 100;
    }

    if (LAST_PC_IS(DENTAL) && THIS_PC_IS(VOWEL))
    {
	F3.Bper = 0;
	A3.Bper = 0;
    }

/*** END OF SPECIAL CASE SPECIFIC CODE *** Insert more above this line */

    /*  C.10.2  -- F2 transitions involving f2back segments are shorter */ 

    if LAST_PC_IS(F2BACK)
      {
	F2.Tcf -= 2;
	A2.Tcf -= 2;
	DBG(printf("rule 10.2 f2 transitions shorter in f2back segments\n"));
      }

    /*  C.10.3 -- Minimum formant separation of f2..f4 is 200 Hz */

    if ((F2.Target - F1.Target) < FADJ(200)) F2.Target = F1.Target + FADJ(200);
    if ((F3.Target - F2.Target) < FADJ(200)) F3.Target = F2.Target + FADJ(200);

    /*  C.10.4 -- Set boundary values and Tcb */

/*  F0.Tcb = F0.Tcf;		   F0.Tcb set in phonetF0()	*/
    F1.Tcb = F1.Tcf;	 	/* C.10.4.1 Assign Tcb's	*/
    F2.Tcb = F2.Tcf;
    F3.Tcb = F3.Tcf;
    A1.Tcb = A1.Tcf;
    A2.Tcb = A2.Tcf;
    A3.Tcb = A3.Tcf;
    AF.Tcb = AF.Tcf;
    AH.Tcb = AH.Tcf;
    AV.Tcb = AV.Tcf;
    MH.Tcb = MH.Tcf;
    MW.Tcb = MW.Tcf;

/* #define BVALF(X)  X.Bvf = (X.Bper*X.Target + (100 - X.Bper)*X.Oldval)/100 */

/* Simplified boundary value formula */
#define BVALF(X)     X.Bvf = X.Oldval + (X.Bper * (X.Target - X.Oldval)) / 100

    BVALF(F0);				/* C.10.4.3 Assign Bvf's	*/
    BVALF(F1);
    BVALF(F2);
    BVALF(F3);
    BVALF(A1);
    BVALF(A2);
    BVALF(A3);
    BVALF(MH);
    BVALF(MW);
/*
    BVALF(AF);				taken care of later
    BVALF(AH);
    BVALF(AV);
*/

    F0.Bvb = F0.Bvf;			/* C.10.4.3 Assign Bvb's	*/
    F1.Bvb = F1.Bvf;
    F2.Bvb = F2.Bvf;
    F3.Bvb = F3.Bvf;
    A1.Bvb = A1.Bvf;
    A2.Bvb = A2.Bvf;
    A3.Bvb = A3.Bvf;
    MH.Bvb = MH.Bvf;
    MW.Bvb = MW.Bvf;

    /*  C.10.5  --  Discontinuous formant jump in a lateral release */

    if LAST_PC_IS(LATERAL)
      {
	F1.Bvf += FADJ(50);
	F2.Bvf += FADJ(50);

	F1.Bvb -= FADJ(50);
	F2.Bvb -= FADJ(50);

	if THIS_PC_IS(VOWEL)  AV.Trantype = DISSMO;
	DBG(printf(" C.10.5\n"));
      }

   /*
    *	C.10.7 -- Special treatment for amplitude parms.
    *	 	  NOTE:  AH.Bvf is set to AH.Target to provide for
    *		         backward only smoothing in the given context.
    */

    AV.Bvf = (AV.Target + AV.Oldval)/2;
    AF.Bvf = (AF.Target + AF.Oldval)/2;
    if (THIS_PC_IS(SONORANT) && LAST_PC_IS(FRICATIVE) && (Aspdur > 0))
	 AH.Bvf = AH.Target;
    else AH.Bvf = (AH.Target + AH.Oldval)/2;
    AV.Bvb = AV.Bvf;
    AF.Bvb = AF.Bvf;
    AH.Bvb = AH.Bvf;
    DBG(printf("C.10.7\n"));

    /*  C.10.8 -- Vowel amplitude offset more gradual */

    if LAST_PC_IS(VOWEL)
      {
	AV.Tcb += 1;				/* was set to 3 */
	DBG(printf("C.10.8\n"));
      }

    /*  C.10.9  --  Voicing offset in stop or fric more gradual, in onset too */
    /*  This now acts as the general offset rule.  New specific rules follow  */

    if (THIS_PC_ISNOT(VOICED) && THIS_PC_ISNOT(SONORANT) && LAST_PC_IS(VOICED))
      {
	AV.Bvb -= 6;
	AV.Bvf  = AV.Bvb;
	DBG(printf("C.10.9.1\n"));
      }

/*
 *  New rules regarding AV   8/10/88
 *  These rules cover the release of plosives voiced & unvoiced
 *  and unvoiced fricatives
 */

    if (THIS_PC_IS(VOICED) && THIS_PC_IS(SONORANT))
    {
	if (LAST_PC_IS(PLOSIVE) && LAST_PC_IS(VOICED))
	{
	    AV.Bvf = AV.Target - 10;
	    AV.Tcf = 1;		/* release of voiced stop has rapid onset */
	}
	else if ( LAST_PC_IS(PLOSIVE) ||
		 (LAST_PC_IS(FRICATIVE) && LAST_PC_ISNOT(VOICED)) )
		        AV.Bvf = AV.Target - 6;
    }

    /* AV offset rule for flap */

    if(Last_PC == PC_DX)
    {
	AV.Tcf = 1;
	AV.Tcb = 1;
    }

    /* AV offset rules */
    
    if (LAST_PC_IS(VOICED) && LAST_PC_IS(SONORANT))
    {
	if THIS_PC_IS(FRICATIVE)
	{
	    AV.Trantype = SETSMO;
	    if THIS_PC_ISNOT(VOICED)	/* unvoiced fricative */
	    {
		AV.Bvf = AV.Oldval - 14;
		AV.Tcb = 5;
	    }
	    else  AV.Tcb = 8;		/* voiced fricative */
	}
	else if THIS_PC_IS(PLOSIVE)
	{
	    AV.Tcb = 4;
	    if THIS_PC_IS(VOICED)  AV.Bvf = AV.Oldval - 18; /* voiced plosive */
	    else
	    {
		AV.Tcb = 1;		/* unvoiced plosive */
		AV.Bvf = AV.Oldval - 12;
		AV.Trantype = SMODIS;
	    }
	}
	else if((This_PC == PC_PE) || (This_PC == PC_QM))  /* sentence ending */
	{
	    AV.Tcb = MIN(Last_dur >> 1, 8);  /* min of 50% of sonor's dur & 8 */
	    AV.Bvf = 20;  /* for a more gradual fade (20 is below audibility) */
	}
	else if(This_PC == PC_DX)	/* AV onset rule for flap */
	{
	    AV.Tcf = 1;
	    AV.Tcb = 1;
	}
    }		/* end AV offset rule */
	
    AV.Bvb = AV.Bvf;	  

    /*  C.10.10  --  Glottal segments have no inherent "articulartory" targs */

    if (LAST_PC_IS(GLOTTAL) || LAST_PC_IS(SILENT))
      {
	F1.Bvf = F1.Bvb = F1.Oldval = F1.Target;
	F2.Bvf = F2.Bvb = F2.Oldval = F2.Target;
	F3.Bvf = F3.Bvb = F3.Oldval = F3.Target;
	A1.Bvf = A1.Bvb = A1.Oldval = A1.Target;
	A2.Bvf = A2.Bvb = A2.Oldval = A2.Target;
	A3.Bvf = A3.Bvb = A3.Oldval = A3.Target;
	DBG(printf("C.10.10 leading glot segs have no inherent artic targs\n"));
      }

    if THIS_PC_IS(SILENT)  /* [. ? , - QX] inherit the Last_PC artic targs */
      {
	F1.Target = F1.Bvb = F1.Bvf = F1.Oldval;
	F2.Target = F2.Bvb = F2.Bvf = F2.Oldval;
	F3.Target = F3.Bvb = F3.Bvf = F3.Oldval;
	A1.Target = A1.Bvb = A1.Bvf = A1.Oldval;
	A2.Target = A2.Bvb = A2.Bvf = A2.Oldval;
	A3.Target = A3.Bvb = A3.Bvf = A3.Oldval;
      }

    /*  C.10.11 - Stops have abrupt fricative offset */

    if LAST_PC_IS(PLOSIVE)
      {
	AF.Bvf = AF.Target;
	DBG(printf("C.10.11\n"));
      }

/*					don't remember why
    if LAST_PC_IS(AFFRICATE)
      {
	AF.Trantype = SETSMO;
	AF.Bvb = AF.Bvf;
	DBG(printf("C.10.111: LastPC affric closure, AF.Trantype = SETSMO\n"));
      }
*/

    if LAST_PC_IS(FRICATIVE)
      {
	if THIS_PC_IS(STOP) AF.Tcb = 2;
	else if THIS_PC_IS(SILENT) AF.Tcb = 9;

	AF.Tcb = MAX(MIN((WORD)(Last_dur)-5, AF.Tcb), 0);
	DBG(printf("rule c.10.12 (ad hoc) adjust AF.Tcb, now=%d\n",AF.Tcb));

	if THIS_PC_ISNOT(FRICATIVE)
	  {
	    AF.Bvf = AF.Bvb = AF.Oldval - 20;
	    DBG(printf("rule c.10.13 (ad hoc) adj af bvf/b, now=%d\n",AF.Bvf));
	  }

      }	

    if (LAST_PC_ISNOT(FRICATIVE) && THIS_PC_IS(FRICATIVE))
      {
	AF.Bvf = AF.Bvb = AF.Target - 15;
	DBG(printf("rule c.10.14 (ad hoc) adjust af.bvb/f, now =%d\n",AF.Bvf));
      }

/***** ULTRA-SPECIAL VERY SPECIFIC CASE HANDLING CODE *****/

    if(((Last_PC == PC_W) || (Last_PC == PC_Y)) && THIS_PC_IS(VOWEL))
    {
	F1.Tcb = 4;   F2.Tcb = 4;   /* F3.Tcb = 4; */
	A1.Tcb = 4;   A2.Tcb = 4;   /* A3.Tcb = 4; */
	F1.Tcf = 6;   F2.Tcf = 6;   /* F3.Tcf = 6; */
	A1.Tcf = 6;   A2.Tcf = 6;   /* A3.Tcf = 6; */
	DBG(printf("c.10.15 (ad hoc): F1-2,A1-2 tcb = 4  F1-2,A1-2 tcf = 6\n"));
    }

    if (((This_PC == PC_W) || (This_PC == PC_Y)) && LAST_PC_IS(VOWEL))
    {
	F1.Tcb = 6;   F2.Tcb = 6;   /* F3.Tcb = 6; */
	A1.Tcb = 6;   A2.Tcb = 6;   /* A3.Tcb = 6; */
	F1.Tcf = 4;   F2.Tcf = 4;   /* F3.Tcf = 4; */
	A1.Tcf = 4;   A2.Tcf = 4;   /* A3.Tcf = 4; */
	DBG(printf("c.10.16 (ad hoc): F1-2,A1-2 tcb = 6  F1-2,A1-2 tcf = 4\n"));
    }

/*  Offset rule for vowel/stop combinations   (ad hoc 2/4/91) */
    if (THIS_PC_IS(STOP) && LAST_PC_IS(VOWEL))
    {
	F1.Tcb = 2;
	AV.Tcb = 2;
	DBG(printf("c.10.16 (ad hoc) PC STOP, last PC VOWEL: F1,AV tcb set to 2\n"));
    }

    if ((iorb->flags & NDF_NEWIORB) && (iorb->articulate == 0))
      {
	F1.Trantype = DISCON;
	F2.Trantype = DISCON;
	F3.Trantype = DISCON;
	A1.Trantype = DISCON;
	A2.Trantype = DISCON;
	A3.Trantype = DISCON;
	AV.Trantype = DISCON;
	AF.Trantype = DISCON;
	AH.Trantype = DISCON;
      }
    MH.Trantype = F1.Trantype;		/* Match mouth timing to F1 */
    MW.Trantype = F1.Trantype;

}  /* end PhonetC10() */

/*
 *   Subroutine PhonetC101()
 *   Assigns Tcf's to obstruents
 */

void PhonetC101(lastseg,thisseg,short_f1) /** thisseg = obstruent on entry */
BOOL  short_f1;
UBYTE lastseg,thisseg;
{

WORD i, temp;

   /*
    *	The following was transplanted (plus mods) from phonetc8.
    */
    DBG(printf("PhonetC101:  assigning TCF to obstruent:"));
    DBG(printf("  last seg=%c%c", Parms[lastseg].digraph >> 8,
		Parms[lastseg].digraph & 0xFF));
    DBG(printf("    this seg=%c%c\n", Parms[thisseg].digraph >> 8,
		Parms[thisseg].digraph & 0xFF));

/*
    if (Parms[lastseg].features & HIGH)
      {
	F1.Tcf = 3;
	F2.Tcf = 2;
	F3.Tcf = 2;
	A1.Tcf = 3;
	A2.Tcf = 2;
	A3.Tcf = 2;
	DBG(printf("rule 8.3.2:\n  f1,a1 tcf now 2   f2,f3,a2,a3 tcf now 1\n"));
      }
    else
*/
      {
	for (i = 0;  i < NUMTCOBSTS;  ++i) if (thisseg == Tcobst[i][0]) break;
	temp = Tcobst[i][1];
	if (short_f1 && LAST_PC_IS(PLOSIVE))
	     F1.Tcf = (temp + 2) >> 1;
	else F1.Tcf = temp;
	F2.Tcf = temp;
	F3.Tcf = temp;
	A1.Tcf = F1.Tcf;
	A2.Tcf = temp;
	A3.Tcf = temp;
	DBG(printf("rule 8.3.3: f1,a1 tcf=%d   f2-a3 tcf=%d\n",F1.Tcf,F2.Tcf));
      }

}  /* end PhonetC101() */

/* ===== phonetf0.c ===== */

/*
*************************************************************************	
*                                                                    	*
*   Copyright 1990, Joseph Katz/Mark Barton.  All rights reserved.	*
*   No part of this program may be reproduced, transmitted, or stored   *
*   in any language or computer system, in any form, whatsoever,	*
*   without the prior written permission of the authors.   		*
*                                                                    	*
*************************************************************************
*/

extern UBYTE *f0start;
extern UBYTE *f0peak;
extern UBYTE *f0end;
extern UBYTE *f0cr;
extern BOOL  syllstart;
extern BOOL  termassign;

#define F0LEFT(x)	*(coef + 7) = (x)
#define F0MIDDLE(x)	*(coef + 7 + ((this_dur >> 1) << 3)) = (x)
#define F0RIGHT(x)	*(coef + 7 + ((this_dur -  1) << 3)) = (x)
#define F0NEXTMIDDLE(x)	*(coef+7+((this_dur<<3)+((next_dur>>1)<<3))) = (x)

void PhonetF0(UBYTE * coef)
{
BOOL phrasefinal, lastvoiced;
WORD this_dur, next_dur;

this_dur = (WORD)This_dur;
next_dur = (WORD)Next_dur;
phrasefinal = (This_bits & PHRASEFINAL) ? TRUE : FALSE;
lastvoiced = (NEXT_PC_IS(SILENT) || NEXT_PC_ISNOT(VOICED) ||
	     (NEXT_PC_IS(STOP) && NEXT_PC_ISNOT(NASAL)))   ? TRUE : FALSE;

if(This_bits & SYLLSTART)
{
    if (LAST_PC_IS(GLOTTAL) && THIS_PC_IS(VOICED))
    {
	F0start = 90 >> 1;			/* 2 Hz steps 		*/
	f0start++;
    }
    else  F0start = (WORD)*f0start++;
    F0peak  = (WORD)*f0peak++;
    F0end   = (WORD)*f0end++;
    ThisCR  = ((WORD)*f0cr++ & 0x0070) >> 2;	/* isolated CR# * 8 (in 2 Hz)*/
    syllstart = TRUE;
    termassign = FALSE;
}

/* if term was assigned, just continue with f0end */
if(termassign)
{
    if(ThisCR)  F0RIGHT(F0end + ThisCR);
    else	F0RIGHT(F0end);
    return;
}

if(syllstart)
{
    termassign = FALSE;
    if THIS_PC_IS(VOICED)
    {
	syllstart = FALSE;
	if THIS_PC_IS(SYLLABIC)  F0LEFT(F0start);
	else if LAST_PC_IS(GLOTTAL)
	{
	    F0LEFT(F0start);
	    F0MIDDLE((F0start + F0peak) >> 1);
	}
	else if(phrasefinal && NEXT_PC_IS(SYLLABIC))  F0MIDDLE(F0start);
	else F0RIGHT(F0start);
    }
}

/* Peak assignments */

if THIS_PC_IS(SYLLABIC)
{
    if(LAST_PC_IS(PLOSIVE) && LAST_PC_ISNOT(VOICED))  F0LEFT(F0peak);
    else if(This_PCS)
    {					/* stressed peak */
	if(phrasefinal)  F0LEFT(F0peak);
	else if(Next_bits & SYLLSTART)  F0MIDDLE(F0peak);
	else F0RIGHT(F0peak);
    }
    else
    {					/* unstressed peak */
	if(phrasefinal)  F0LEFT(F0peak);
	else		 F0MIDDLE(F0peak);
    }
    if(!phrasefinal && !ThisCR)
    {					/* assign fall */
	if(Next_bits & SYLLSTART)  F0RIGHT(F0end);
	else			   F0NEXTMIDDLE(F0end);
    }
}

if(phrasefinal && lastvoiced && !ThisCR)
{   F0RIGHT(F0end);				/* assign term */
    termassign = TRUE;
    return;
}

if(phrasefinal && ThisCR)			/* assign continuation rises */
{
    if THIS_PC_IS(SYLLABIC)  F0MIDDLE(F0end);
    if(lastvoiced)
    {
	F0RIGHT(F0end + ThisCR);
	termassign = TRUE;
    }
    return;
}

}  /* end phonetf0() */
